In [1]:
import numpy as np
import csv
import pandas as pd
from itertools import islice
import json
import matplotlib.pyplot as plt
pd.set_option("display.max_rows", None)

In [2]:
books = pd.read_csv('data/final_book_dataset_cleaned.csv', sep = '\t',
        dtype={
            'author_birthyear' : 'Int64',
            'title_id' : 'Int64',
            'isbn' : 'str'
        }
    )

In [3]:
books.head(5)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus
0,9372,The Long Loud Silence,Wilson Tucker,1954,1954-00-00,Dell,1914,"Deer Creek, Illinois, USA",0899683754,Publisher's description: Tomorrow's war -- the...,"['Anatomy of Wonder 1 Core Collection', 'biolo...",False,False
1,2215181,Mrs. Candy Strikes It Rich,Robert Tallant,1954,1954-00-00,Doubleday,1909,"New Orleans, Louisiana, USA",NaN,NaN,NaN,False,False
2,1392436,Return to the Lost Planet,Angus MacVicar,1954,1954-00-00,Burke,1908,"Duror, Argyll, Scotland, UK",NaN,NaN,NaN,False,False
3,1112206,Rainbow on the Road,Esther Forbes,1954,1954-00-00,Houghton Mifflin,1891,"Westborough, Massachusetts, USA",NaN,NaN,NaN,False,False
4,1908,The Forgotten Planet,Murray Leinster,1954,1954-00-00,Ace Books,1896,"Norfolk, Virginia, USA",0881846163,"**From the first page of the Ace Double:** ""Na...","['insects', 'Librivox', 'Project Gutenberg', '...",False,False

In [4]:
## add month of publication column, 00 means only year is known
books['month_of_publication'] =books['release_date'].str[5:7].str.replace('00','Unknown')
books.sample(50)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus,month_of_publication
30782,19906,Darkest Hour,Mark Chadbourn,2000,2000-10-00,Gollancz,1960,"Ashby-de-la-Zouch, Leicestershire, England, UK",0575069031,NaN,['fantasy'],False,False,10
54559,1223179,Cornerstonia: The Rose River Journey,V. M. Rosario,2010,2010-10-25,Cornerstonia,<NA>,NaN,9780982858806,NaN,NaN,False,False,10
143359,3575942,Ghost Therapy,Mark Rosendorf,2024,2024-10-02,The Wild Rose Press,<NA>,NaN,9781509258239.0,NaN,['young-adult ghost story'],False,False,10
72599,3376269,Mona Livelong: Paranormal Detective,Valjeanne Jeffers,2013,2013-10-25,Valjeanne Jeffers,1967,USA,9781493591008.0,NaN,NaN,False,False,10
145569,3351766,The Witch of Wol Sin Lake,Lena Jeong,2024,2024-10-29,Harper,<NA>,NaN,9780063241701.0,After her fraught journey to save her queendom...,"['Fantasy', 'Young Adult']",False,False,10
50272,1268517,The Fight for the Frozen Land: Arctic,Elizabeth Singer Hunt,2009,2009-02-05,Red Fox,1970,"Roanoke, Virginia, USA",9781862306332,NaN,['juvenile sf'],False,False,02
17152,1113563,Spring-Heeled Jack,Philip Pullman,1989,1989-00-00,Alfred A. Knopf,1946,"Norwich, Norfolk, England, UK",0679810579,Three children make their escape from a London...,"['Fantasy', 'Young Adult', 'Adventure']",False,False,Unknown
30209,791721,The PowerBook,Jeanette Winterson,2000,2000-09-00,Alfred A. Knopf,1959,"Manchester, Lancashire, England, UK",0375411119,NaN,NaN,False,False,09
29038,19877,The Fata Morgana,Leo Frankowski,1999,1999-08-00,Baen Books,1943,"Detroit, Michigan, USA",0671578227,NaN,['lost race'],False,False,08
78147,1758585,Jerry's Magic,W. W. Rowe,2014,2014-09-07,Larson Publications,1934,NaN,9781936012664.0,NaN,['juvenile fantasy'],False,False,09
67385,3027173,MoriaVaratu,David Lee Jones (I),2012,2012-01-25,Darkside Planet Press,<NA>,NaN,NaN,NaN,NaN,False,False,01
15243,1543,Memoirs of an Invisible Man,H. F. Saint,1987,1987-02-00,Penguin Books,1941,"New York City, New York, USA",0140107223,NaN,['science fiction'],False,False,02
82750,1937677,The Dragon Prince,Patty Jansen,2015,2015-10-06,Capricornica Publications,<NA>,NaN,9781517709501.0,NaN,['historical fantasy'],False,False,10
140574,3202535,New Eden,Ruth Fox,2023,2023-08-22,CamCat Publishing,<NA>,NaN,9780744309706.0,NaN,[],False,False,08
80809,2338095,Fractured,Suzanne Wright,2015,2015-12-14,Suzanne Wright,<NA>,"England, UK",9781532892066.0,NaN,['vampires'],False,False,12
27222,9847,The Seven Songs of Merlin,T. A. Barron,1997,1997-09-00,Philomel Books,1952,"Boston, Massachusetts, USA",039923019X,From copyright page: Having stumbled upon his ...,"['Merlin', 'ofearna-ebooks', 'wizards', 'young...",False,False,09
1668,8952,The Monster Men,Edgar Rice Burroughs,1962,1962-05-17,Ace Books,1875,"Chicago, Illinois, USA",0345378326,NaN,['Project Gutenberg'],False,False,05
124089,2813143,Double Magic,Lyndon Hardy,2020,2020-11-17,Bartizan Press,1941,"Los Angeles, California, USA",9781733095082.0,NaN,['fantasy'],False,False,11
20949,15180,Thunder in the Sky,William Sarabande,1992,1992-11-00,Bantam Books,1942,"Hollywood, California, USA",0553291068,The grassy Great Plains shake with thunder and...,"['Fiction', 'Fantasy']",False,False,11
98763,2332409,Erebus,Ralph Kern,2017,2017-09-13,Ralph Kern,<NA>,UK,NaN,NaN,NaN,False,False,09
106609,2597338,Listen to Me Now,A. I. Nasser,2018,2018-12-27,Scare Street,<NA>,NaN,9781792745072.0,NaN,['horror'],False,False,12
566,1018668,Worzel Gummidge at the Circus,Barbara Euphan Todd,1956,1956-00-00,Evans Brothers,1890,"Doncaster, West Riding of Yorkshire, England, UK",0426201280,NaN,NaN,False,False,Unknown
50299,1265970,I Am the Angel,Michael Stuart,2009,2009-06-17,iUniverse,<NA>,NaN,9780595485031,NaN,NaN,False,False,06
108152,2370883,A Hint of Hydra,"Kati Bartkowski, Heidi Lang",2018,2018-07-10,Aladdin,<NA>,NaN,9781481477956.0,NaN,['juvenile fantasy'],False,False,07
90892,2137271,From Moon to Joshua,Matthew Moffitt,2016,2016-11-23,Edge Science Fiction and Fantasy Publishing,<NA>,NaN,9781770531376.0,NaN,"['dystopia', 'science fiction', 'weird west']",False,False,11
31751,22049,Swim the Moon,Paul Brandon,2001,2001-09-00,Tor,1971,"Kent, England, UK",0312877943,NaN,['selkies'],False,False,09
137443,3161599,The Isles of the Gods,Amie Kaufman,2023,2023-05-02,Alfred A. Knopf,1980,"Melbourne, Victoria, Australia",9780593479285.0,"Magic, romance, and slumbering gods clash in t...","['young-adult fantasy', 'Fantasy', 'Young Adul...",False,False,05
78194,1760129,The 12 Screams of Christmas,R. L. Stine,2014,2014-09-30,Scholastic,1943,"Columbus, Ohio, USA",9780545627771.0,NaN,['juvenile horror'],False,False,09
58548,1208366,Tempest's Legacy,Nicole Peeler,2011,2011-01-01,Orbit (US),1978,"Aurora, Illinois, USA",9780316056601,NaN,"['urban fantasy', 'Fantasy', 'Young Adult']",False,False,01
84529,1842189,The Imagination Box,Martyn Ford,2015,2015-05-05,Faber and Faber,<NA>,NaN,9780571311668.0,NaN,['juvenile fantasy'],False,False,05
76472,2342400,Darlin' Clementine,Crystal Dawn,2014,2014-09-30,Crystal Dawn,<NA>,NaN,9781310749872.0,NaN,NaN,False,False,09
128337,2988158,Call of Destiny,P. R. Adams,2021,2021-07-16,Promethean Tales,<NA>,NaN,NaN,NaN,NaN,False,False,07
60040,1551018,"Hell Is for Real, Too",Skip Shmuley,2011,2011-11-23,Plume / Penguin,<NA>,NaN,9780452297791,NaN,NaN,False,False,11
9585,1788423,Kommando 55,Michael Hughes (I),1980,1980-00-00,New English Library,1940,"Scotland, UK",0450051730,NaN,NaN,False,False,Unknown
119614,2753506,Queen of Coin and Whispers,Helen Corcoran,2020,2020-06-01,The O'Brien Press,<NA>,NaN,9781788491181.0,NaN,"['young-adult fantasy', 'Fantasy', 'Young Adul...",False,False,06
39141,1942542,The Kinshield Legacy,K. C. May,2005,2005-12-20,Archebooks Publishing,<NA>,NaN,1595071164,NaN,"['fantasy', 'Fantasy', 'Adventure', 'Science f...",False,False,12
118587,2982384,Rock On,N. A. Rossi,2020,2020-11-23,Resista Press,<NA>,NaN,9781913417048.0,NaN,NaN,False,False,11
95298,2807962,A Fox's Revenge,Brandon Varnell,2017,2017-10-10,Kitsune Incorporated,<NA>,NaN,9781977610164.0,NaN,NaN,False,False,10
6814,186966,In Caverns Below,Stanton A. Coblentz,1975,1975-10-00,Garland Publishing,1896,"San Francisco, California, USA",0824014057,"Available on page 76, [Bleiler (Gernsback)](ht...","['heat ray', 'underground cities']",False,False,10
41938,1234986,The Weathermage,Linda Smith,2006,2006-09-22,Coteau Books,1949,"Lethbridge, Alberta, Canada",1550503529,NaN,NaN,False,False,09
73314,1599008,Starglass,Phoebe North,2013,2013-07-23,Simon & Schuster Books for Young Readers,<NA>,"New Jersey, USA",9781442459533.0,"For all of her sixteen years, Terra has lived ...","['generation starship', 'young-adult sf', 'Fic...",False,False,07
127661,3017931,"It's Not You, It's Me",Gabrielle Williams,2021,2021-08-31,Allen & Unwin (Australia),1963,NaN,9781760526078.0,NaN,NaN,False,False,08
31160,22086,Year of the Griffin,Diana Wynne Jones,2000,2000-10-00,Gollancz,1934,"Hornsey, Middlesex, England, UK",0575070463,"Elda, the griffin daughter of the great Wizard...","['young-adult fantasy', 'Fantasy', 'Young Adul...",False,True,10
74687,1669476,Dragon Soldiers,J. Allan Danelek,2014,2014-02-15,Adventures Unlimited Press,<NA>,NaN,9781939149183.0,NaN,['dinosaurs'],False,False,02
72809,1631264,Montaro Caine,Sidney Poitier,2013,2013-05-07,Spiegel & Grau,1927,"Miami, Florida, USA",9780385531115.0,The first novel from the beloved actor and dir...,"['literary fantasy', 'metaphysical fantasy', '...",False,False,05
79941,2207492,Jaguar at the Portal,Aimee Easterling,2015,2015-07-10,Wetknee Books,<NA>,NaN,9781515016960.0,NaN,"['paranormal romance', 'shapechangers']",False,False,07
108626,2652633,The Witch Queen,Juliana Haygert,2018,2018-04-10,Juliana Haygert,<NA>,NaN,9781987723113.0,NaN,NaN,False,False,04
106294,2604954,Luck of the Witch,K. E. O'Connor,2018,2018-08-22,K. E. O'Connor,<NA>,NaN,9781916357396.0,NaN,['witches'],False,False,08
61160,1583139,The Haunting of Charity Delafield,Ian Beck,2011,2011-11-03,The Bodley Head,1947,"Brighton, East Sussex, England, UK",9780370332109,NaN,['juvenile fantasy'],False,False,11
75360,1696563,Unicorn Prince,Zanna Davidson,2014,2014-03-01,Usborne,<NA>,NaN,9781409506362.0,NaN,['juvenile fantasy'],False,False,03

In [5]:
## Add age of author at publication
books['Author_Age_at_Publication'] = 'Unknown'
books['Author_Age_at_Publication'] = books['Author_Age_at_Publication'].case_when([(books['author_birthyear'].isna() == False,books['release_year'] - books['author_birthyear'])])

In [6]:
books.sample(15)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus,month_of_publication,Author_Age_at_Publication
57165,1254317,Unforsaken,Sophie Littlefield,2011,2011-10-11,Delacorte Press,<NA>,NaN,9780385738545,NaN,['young-adult fantasy'],False,False,10,Unknown
73444,1711689,The Lovely and the Lost,Page Morgan,2014,2014-05-01,Hot Key Books,<NA>,NaN,9781471402555.0,NaN,"['demons', 'gargoyles', 'historical fantasy', ...",False,False,05,Unknown
103118,3345048,Wisteria Wrinkle,Angela Pepper,2018,2018-07-28,Angela Pepper Publishing,<NA>,NaN,9781777672768.0,NaN,NaN,False,False,07,Unknown
104911,2485399,For Love of Evil,Auryn Hadley,2018,2018-11-21,Spotted Horse Productions,<NA>,NaN,9781731166180.0,NaN,NaN,False,False,11,Unknown
43818,1230457,The Sibyl's Urn,John T. Cullen,2007,2007-05-01,Clocktower Books,1949,NaN,9780743309066,NaN,NaN,False,False,05,58
144772,3316106,Grim Root,Bonnie Jo Stufflebeam,2024,2024-06-04,Dark Matter Ink,<NA>,NaN,9781958598368.0,NaN,['horror'],False,False,06,Unknown
22261,19853,Jane Eyre,Charlotte Brontë,1994,1994-00-00,Wordsworth Editions,1816,"Thornton, West Riding of Yorkshire, England, UK",1853268348,"""The orphaned Jane Eyre is no beauty but her p...","['1001 Books You Must Read Before You Die', 'h...",False,False,Unknown,178
31181,22071,The Dastard,Piers Anthony,2000,2000-10-00,Tor,1934,"Oxford, Oxfordshire, England, UK",0812574737,NaN,['fantasy'],False,False,10,66
139051,3385620,Of Bones and Skulls,Samantha Ziegler,2023,2023-04-26,Finished Fiction,<NA>,NaN,9798987953419.0,NaN,NaN,False,False,04,Unknown
100477,2132305,Future Threat,Elizabeth Briggs,2017,2017-03-01,AW Teen,<NA>,NaN,9780807526842.0,Elena Martinez survived the future. But the fi...,"['dystopia', 'time travel', 'young-adult sf', ...",False,False,03,Unknown
123486,2905027,Dungeons and Demons,Kayla Krantz,2020,2020-10-20,Fire Quill Publishing,<NA>,"Roseville, Macomb, Michigan, USA",9781950530113.0,NaN,NaN,False,False,10,Unknown
6732,896630,The Golden Age,Constantine FitzGibbon,1975,1975-00-00,W. W. Norton & Company,1919,"Lenox, Massachusetts, USA",0393086836,NaN,NaN,False,False,Unknown,56
7640,7959,Survivor,Laurence M. Janifer,1977,1977-08-00,Ace Books,1933,"Brooklyn, New York City, New York, USA",0441791115,"Gerald Knave, Survivor, decides to vacation on...","['aliens', 'science fiction', 'telepathy']",False,False,08,44
83563,1756086,Heart of the Hawk,Justine Davis,2015,2015-04-16,Bell Bridge Books,<NA>,"Iowa, USA",9781611946192.0,NaN,"['historical fantasy', 'paranormal romance', '...",False,False,04,Unknown
1404,826213,If the South Had Won the Civil War,MacKinlay Kantor,1961,1961-04-00,Forge,1904,"Webster City, Iowa, USA",0312869495,if you have ever wondered what the consequence...,[],False,False,04,57

In [7]:
## Add column with number of hugo or locus awards won prior to that date
books['Hugo_Awards_Previously']= books.groupby(['author'])['hugo'].cumsum()
books['Locus_Awards_Previously']= books.groupby(['author'])['locus'].cumsum()

In [8]:
books.sample(15)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously
13518,10680,Galaxy Four,William Emms,1985,1985-11-00,W. H. Allen,1930,Australia,0491036914,NaN,NaN,False,False,11,55,0,0
116937,2619045,Cole Blooded,"Outspan Foster, Blaise Corvin",2019,2019-09-03,Adom Publishing,<NA>,NaN,9781690662235.0,NaN,NaN,False,False,09,Unknown,0,0
83148,1914366,An Explorer's Guide to the Nether,Winter Morgan,2015,2015-11-03,Sky Pony Press,<NA>,NaN,9781510703513.0,NaN,"['juvenile sf', 'video games']",False,False,11,Unknown,0,0
23201,12437,Scorpianne,Emily Devenport,1994,1994-08-00,Roc,1958,NaN,0451453182,On Earth Lucy has long been one of the best in...,[],False,False,08,36,0,0
74099,2644606,Gilded Wings,Cameo Renae,2014,2014-12-18,Crushing Hearts and Black Butterfly Publishing,<NA>,"San Francisco, California, USA",9781939769718.0,NaN,NaN,False,False,12,Unknown,0,0
109515,2346734,The Beast's Heart,Leife Shallcross,2018,2018-04-24,Hodder & Stoughton,<NA>,NaN,9781473668713.0,NaN,"['fantasy', 'retold fairy tales']",False,False,04,Unknown,0,0
108657,2367371,Whiskey on the Rocks,S. M. Blooding,2018,2018-04-02,Whistling Book Press,<NA>,NaN,9781947790209.0,NaN,['urban fantasy'],False,False,04,Unknown,0,0
37012,155434,The Certification of America: The Decline and ...,Paul Seifert,2004,2004-05-00,iUniverse,<NA>,NaN,0595314988,NaN,NaN,False,False,05,Unknown,0,0
79733,2239585,Corrigan Lust,Helen Harper,2015,2015-12-27,Helen Harper,<NA>,"Scotland, UK",NaN,NaN,"['fantasy', 'magic', 'paranormal', 'romance', ...",False,False,12,Unknown,0,0
119605,2753478,Maelstrom,Sonia Orin Lyris,2020,2020-07-14,Knotted Road Press,<NA>,NaN,9781644701614.0,NaN,['fantasy'],False,False,07,Unknown,0,0
147252,3425028,Awakening,L. Higginson,2024,2024-02-23,Beyond the Vale Publishing,<NA>,NaN,9780796135728.0,NaN,['fantasy'],False,False,02,Unknown,0,0
134947,3152191,The Clackity,Lora Senf,2022,2022-06-28,Atheneum Books for Young Readers,<NA>,NaN,9781665902670.0,NaN,"['juvenile fantasy', 'juvenile horror']",False,False,06,Unknown,0,0
19471,3168548,Spellbound,D. F. Mills,1991,1991-03-00,Diamond Books,<NA>,NaN,1557734720,NaN,NaN,False,False,03,Unknown,0,0
13426,21592,Moscow Rules,Robert Moss,1985,1985-12-00,Pocket Books,1946,"Melbourne, Australia",0671558137,"""Moscow Rules"" is a 1985 political thriller ab...",NaN,False,False,12,39,0,0
50600,1149448,Personal Effects: Dark Art,"Jordan Weisman, J. C. Hutchins",2009,2009-06-09,St. Martin's Griffin,1960,NaN,9780312383824,NaN,[],False,False,06,49,0,0

In [9]:
## Add column with boolean if author been nominated for Hugo/Locus prior to that date
books['Hugo_Nominee_Before'] = 'False'
books['Hugo_Nominee_Before'] = books['Hugo_Nominee_Before'].case_when([(books['Hugo_Awards_Previously'] > 0,True)])
books['Locus_Nominee_Before'] = 'False'
books['Locus_Nominee_Before'] = books['Locus_Nominee_Before'].case_when([(books['Locus_Awards_Previously'] > 0,True)])

In [10]:
books.sample(100)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before
79733,2239585,Corrigan Lust,Helen Harper,2015,2015-12-27,Helen Harper,<NA>,"Scotland, UK",NaN,NaN,"['fantasy', 'magic', 'paranormal', 'romance', ...",False,False,12,Unknown,0,0,False,False
118522,3038584,Blood Brothers,R. L. King,2020,2020-06-15,Magespace Press,<NA>,NaN,9781734096156.0,Alastair Stone figures using tracking magic to...,['Fantasy'],False,False,06,Unknown,0,0,False,False
44214,222991,Conversations with the Devil,Jeff Rovin,2007,2007-03-00,Forge,1951,"Brooklyn, New York, USA",0765307030,NaN,[],False,False,03,56,0,0,False,False
5946,2006971,The Stronghold,Mollie Hunter,1974,1974-00-00,Hamish Hamilton,1922,"Longniddry, East Lothian, Scotland, UK",0241890268,"Crippled in a Roman raid on his native island,...",['druids'],False,False,Unknown,52,0,0,False,False
112402,2529235,Legend,Nicole Conway,2019,2019-05-07,Month9Books,<NA>,"Decatur, Alabama, USA",9781948671361.0,"In a war of gods and tyrants, the will of the ...",['young-adult fantasy'],False,False,05,Unknown,0,0,False,False
60530,1352114,Angels Cry,J. S. Wayne,2011,2011-09-07,Noble Romance Publishing,1977,"Amarillo, Texas, USA",9781605927077,NaN,NaN,False,False,09,34,0,0,False,False
42826,180662,Engaging the Enemy,Elizabeth Moon,2006,2006-00-00,Del Rey / Ballantine,1945,"McAllen, Texas, USA",0345447565,Kylara Vatta has had to leave a glowing future...,"['female main character', 'ofearna-ebooks', 's...",False,False,Unknown,61,1,3,True,True
96332,2210451,Rules for Thieves,Alexandra Ott,2017,2017-06-06,Aladdin,<NA>,NaN,9781481472746.0,NaN,"['curses', 'juvenile fantasy']",False,False,06,Unknown,0,0,False,False
68814,2932089,Sam & Skully,Dewey Badeaux,2013,2013-00-00,Alligator Press,<NA>,NaN,9780988405745.0,"""Sam McDonnell isn't like the other kids in sc...",['Texas'],False,False,Unknown,Unknown,0,0,False,False
2692,1011452,Claimed,Francis Stevens,1966,1966-00-00,Renaissance E Books,1883,"Minneapolis, Minnesota, USA",1588731804,"**From the flaps of the Avalon edition:** ""It ...","['New Jersey', 'pgas', 'prehistoric god', 'sci...",False,False,Unknown,83,0,0,False,False
108024,2531047,Soulless at Sunset,Deanna Chase,2018,2018-03-02,Bayou Moon Publishing,<NA>,"California, USA",9781940299532.0,NaN,"['paranormal romance', 'urban fantasy', 'vampi...",False,False,03,Unknown,0,0,False,False
46921,2182874,Fish and Sphinx,Rae Bridgman,2008,2008-04-11,Great Plains Teen Fiction,<NA>,NaN,9781894283816,"In this rollicking fishy tale, two eleven—year...",NaN,False,False,04,Unknown,0,0,False,False
6561,11874,Endless Voyage,Marion Zimmer Bradley,1975,1975-05-00,Ace Books,1930,"Albany, New York, USA",0441206603,This is set far in the future when humans can ...,"['generation ship', 'science fiction']",False,False,05,45,1,0,True,False
43856,907905,The Castle in the Forest,Norman Mailer,2007,2007-01-00,Random House,1923,"Long Branch, New Jersey, USA",9781588365903,NaN,"['Austria', 'demons', 'fantasy', 'genealogy', ...",False,False,01,84,0,0,False,False
33515,24331,Dead Time,Andrew Neiderman,2002,2002-03-00,Pocket Star Books,1940,"Brooklyn, New York City, New York, USA",0743412680,NaN,['horror'],False,False,03,62,0,0,False,False
31738,22834,Aftershocks,Harry Turtledove,2001,2001-02-00,Del Rey / Ballantine,1949,"Los Angeles, California, USA",0345430212,"""ONE OF THE MOST MEMORABLE SERIES OF ALTERNATI...",['alternate history'],False,False,02,52,0,0,False,False
54800,1165424,Tyger Tyger,Kersten Hamilton,2010,2010-11-15,Clarion Books,1958,"High Rolls, New Mexico, USA",9780547330082,Soon after the mysterious and alluring Finn ar...,"['goblins', 'urban fantasy', 'young-adult fant...",False,False,11,52,0,0,False,False
5835,8446,Murder's Shield,"Richard Sapir, Warren Murphy",1973,1973-04-00,Pinnacle Books,1936,"New York City, New York, USA",NaN,NaN,NaN,False,False,04,37,0,0,False,False
80933,2244683,The Shadow King,Heather Killough-Walden,2015,2015-11-26,Heather Killough-Walden,<NA>,"California, USA",9781665235426.0,NaN,NaN,False,False,11,Unknown,0,0,False,False
135876,3085756,Siren Song,J. E. Cluney,2022,2022-11-20,Cosmic Publishing,<NA>,NaN,9798325708558.0,NaN,NaN,False,False,11,Unknown,0,0,False,False
8973,3122378,"Polly, the Worried",Katheryn Kimbrough,1979,1979-00-00,Popular Library,1929,NaN,0445043431,NaN,NaN,False,False,Unknown,50,0,0,False,False
118171,2950979,Jason Jupiter: Lost and Found,Albert M. Manaford,2020,2020-06-17,Archway Publishing,<NA>,NaN,9781480890398.0,NaN,['young-adult sf'],False,False,06,Unknown,0,0,False,False
24651,19327,"Arthur, King",Dennis Lee Anderson,1995,1995-01-00,HarperPrism,<NA>,NaN,006105433X,NaN,['historical fantasy'],False,False,01,Unknown,0,0,False,False
90222,2082418,"Forever, Again",Victoria Laurie,2016,2016-12-13,Disney/Hyperion Books,1966,"MIchigan, USA",9781484700099.0,"""Sixteen-year-old Lily Bennett becomes wrapped...","['paranormal romance', 'young-adult fantasy']",False,False,12,50,0,0,False,False
148318,3071831,Sporemageddon,RavensDagger,2025,2025-07-07,Mango Media,<NA>,NaN,9798834609711.0,"Nature is dying, but perhaps before the world ...","['Fantasy', 'Young Adult', 'Science Fiction', ...",False,False,07,Unknown,0,0,False,False
128825,2922075,A Dragon's Dare,"Michael Anderle, Auburn Tempest",2021,2021-09-01,LMBPN Publishing,<NA>,NaN,9781685004347.0,"Ye screw with this lass, ye get put on yer ass...","['Fantasy', 'Fiction']",False,False,09,Unknown,0,0,False,False
62030,1336174,Wasted II,Alastair Sinclair,2011,2011-09-09,Olympia Publishers,<NA>,NaN,9781848971608,NaN,NaN,False,False,09,Unknown,0,0,False,False
15235,1558,A Mask for the General,Lisa Goldstein,1987,1987-11-00,Legend,1953,"Los Angeles, California, USA",0099648806,NaN,NaN,False,True,11,34,0,2,False,True
117160,2616891,Granny Magic,Elka Evalds,2019,2019-11-07,Chicken House,<NA>,NaN,9781912626199.0,NaN,NaN,False,False,11,Unknown,0,0,False,False
120492,2780165,A Storm of Blood and Stone,Galen Surlak-Ramsey,2020,2020-10-27,Tiny Fox Press,<NA>,NaN,9781946501288.0,NaN,['fantasy'],False,False,10,Unknown,0,0,False,False
138746,3549907,Horus,Laura Greenwood,2023,2023-11-30,Naughty Nights Press,<NA>,UK,9781773575834.0,NaN,NaN,False,False,11,Unknown,0,0,False,False
67177,1457112,When Diplomacy Fails ...,Michael Z. Williamson,2012,2012-08-00,Baen Books,1967,"Birkenhead, Cheshire, England, UK",9781451637908.0,#7 in the Freehold Universe series. Science fi...,"['military sf', 'Adventure', 'Fiction', 'Scien...",False,False,08,45,0,0,False,False
104459,2413017,Beneath the Lighthouse,Julieanne Lynch,2018,2018-06-26,Vesuvian Books,<NA>,NaN,9781944109189.0,NaN,NaN,False,False,06,Unknown,0,0,False,False
146202,3369983,Blood of the Gods,Sapir A. Englard,2024,2024-11-19,Montlake Romance,<NA>,NaN,9781662522277.0,NaN,"['fantasy', 'romantasy']",False,False,11,Unknown,0,0,False,False
39310,174542,Dark Tales: Tales from a Twisted Imagination,Daniel Luther Hart,2005,2005-01-31,AuthorHouse,<NA>,NaN,142081608X,NaN,NaN,False,False,01,Unknown,0,0,False,False
41437,3585861,The Kytos Project,John Von Kesmark,2006,2006-10-15,Book Guild Publishing,<NA>,NaN,1846240476,NaN,NaN,False,False,10,Unknown,0,0,False,False
146750,3330042,Another Vampire Love Story,H. T. Night,2024,2024-01-09,H. T. Night,<NA>,NaN,NaN,NaN,NaN,False,False,01,Unknown,0,0,False,False
10537,1347,Radix,A. A. Attanasio,1981,1981-07-00,New English Library,1951,"Newark, New Jersey, USA",034061840X,NaN,"['nebula award for best novel finalist', 'scie...",False,True,07,30,0,1,False,True
85005,1998250,Chaos: Worlds Beyond,C. W. Holcomb,2015,2015-02-28,CreateSpace,<NA>,NaN,9781508426202.0,NaN,NaN,False,False,02,Unknown,0,0,False,False
44174,222691,Moonshine,Rob Thurman,2007,2007-03-00,Roc / New American Library,<NA>,NaN,9780451461391,After saving the world from his fiendish fathe...,"['ofearna-2007', 'ofearna-2017', 'ofearna-audi...",False,False,03,Unknown,0,0,False,False
22979,14075,Queen Eleanor's Legacy,Atarah Ben-Tovim,1994,1994-04-00,Piatkus,1940,"Wales, UK",0749902264,NaN,['fantasy'],False,False,04,54,0,0,False,False
18763,12913,Victoria,Ruby Jean Jensen,1990,1990-12-00,Zebra Books / Kensington Publishing Corp.,1927,"McDonald County, Missouri, USA",0821732358,When Fawn inherits her late grandfather's deca...,"['dolls', 'horror']",False,False,12,63,0,0,False,False
83524,1830497,Monster,Keith Ferrario,2015,2015-04-07,Samhain Publishing,<NA>,"Duluth, Minnesota, USA",9781619227774.0,NaN,['horror'],False,False,04,Unknown,0,0,False,False
112118,3404462,Ferrum Corde,Richard Fox,2019,2019-01-15,Triplane Press,1978,NaN,9781794370821.0,The Terran Union must launch one last desperat...,"['Adventure', 'Science fiction', 'Aliens']",False,False,01,41,0,0,False,False
53037,1139742,The Questing Road,Lyn McConchie,2010,2010-08-03,Tor Fantasy,1946,"Auckland, New Zealand",9780765361929,NaN,NaN,False,False,08,64,0,0,False,False
110862,2517903,The Spirits of Six Minstrel Run,Matthew S. Cox,2019,2019-01-18,Division Zero Press,<NA>,NaN,9781949174946.0,NaN,"['ghosts', 'haunted house', 'horror']",False,False,01,Unknown,0,0,False,False
129884,2789466,Zoraida Grey and the Pictish Runes,Sorchia DuBois,2021,2021-01-27,Sorchia DuBois,<NA>,NaN,9798697005675.0,NaN,['fantasy'],False,False,01,Unknown,0,0,False,False
149487,3440659,When the Wolf Comes Home,Nat Cassidy,2025,2025-04-22,Tor Nightfire,1981,"North Carolina, USA",9781250354341.0,"One night, Jess, a struggling actress, finds a...","['horror', 'Fiction', 'Fantasy', 'Psychologica...",False,False,04,44,0,0,False,False
54898,1071052,Moon Craving,Lucy Monroe,2010,2010-02-01,Berkley Sensation,1967,NaN,9781101171660,(The second book in the Children of the Moon s...,"['paranormal romance', 'Fiction', 'Romance', '...",False,False,02,43,0,0,False,False
115805,3218847,The Scepter of Fire,Morgan Rice,2019,2019-06-25,Morgan Rice,<NA>,NaN,9781094310961.0,NaN,NaN,False,False,06,Unknown,0,0,False,False
130979,2866179,Euphoria Kids,Alison Evans,2021,2021-06-01,Echo Publishing,<NA>,NaN,9781760685850.0,NaN,['young-adult fantasy'],False,False,06,Unknown,0,0,False,False
30632,26774,The Rebel,Melinda Metz,2000,2000-06-00,Pocket Pulse,<NA>,NaN,0671035622,Michael has finally found the one thing he alw...,['young-adult sf'],False,False,06,Unknown,0,0,False,False
27666,21687,The Ice People,Maggie Gee,1998,1998-00-00,Richard Cohen,1948,"Poole, Dorset, England, UK",186066153X,NaN,"['cosy catastrophe', 'Fiction', 'Science ficti...",False,False,Unknown,50,0,0,False,False
78065,1761941,Origins,Richard Brown (US),2014,2014-05-22,Incendiary Books,<NA>,NaN,9780615998282.0,NaN,"['post apocalypse', 'zombies']",False,False,05,Unknown,0,0,False,False
130134,2826338,The Salt in Our Blood,Ava Morgyn,2021,2021-03-02,AW Teen,<NA>,NaN,9780807572276.0,"Ten years ago, Cat's volatile mother, Mary, le...","['young-adult fantasy', 'Young Adult Fiction',...",False,False,03,Unknown,0,0,False,False
25637,3584988,FlashPoint,"Curtis Taylor, Todd Hester",1996,1996-04-00,Gold Leaf Press,<NA>,NaN,1882723546,NaN,NaN,False,False,04,Unknown,0,0,False,False
117350,2611651,Invasion of the DeadSpores: Today San Diego - ...,Rok Chilla,2019,2019-07-31,Clocktower Books,<NA>,NaN,9780743322645.0,NaN,NaN,False,False,07,Unknown,0,0,False,False
83358,1815839,Dino-Mike and the Museum Mayhem,Franco,2015,2015-01-01,Stone Arch Books,<NA>,NaN,9781496503145.0,NaN,"['dinosaurs', 'juvenile sf']",False,False,01,Unknown,0,0,False,False
142636,3217297,The Memory Thieves,Dhonielle Clayton,2023,2023-09-26,Henry Holt,1983,"Olney, Maryland, USA",9781250174970.0,NaN,['juvenile fantasy'],False,False,09,40,0,0,False,False
138733,3549898,Seth,Laura Greenwood,2023,2023-02-21,Naughty Nights Press,<NA>,UK,9781773574691.0,NaN,NaN,False,False,02,Unknown,0,0,False,False
67993,1980937,Light,'Nathan Burgoine,2013,2013-10-13,Bold Strokes Books,<NA>,UK,9781602829954.0,NaN,NaN,False,False,10,Unknown,0,0,False,False
31116,22104,Worse Than Death,Sherry Gottlieb,2000,2000-01-00,Forge,1948,"Los Angeles, California, USA",0312873921,NaN,NaN,False,False,01,52,0,0,False,False
101502,2110405,One Blood Ruby,Melissa Marr,2017,2017-02-28,Harper,1972,"Pennsylvania, USA",9780062084163.0,NaN,"['faeries', 'young-adult fantasy', 'Fantasy', ...",False,False,02,45,0,0,False,False
39178,174091,Deja Vu,Ian Hocking,2005,2005-01-31,Uka Press,1976,"Truro, Cornwall, England, UK",1904781152,NaN,NaN,False,False,01,29,0,0,False,False
34261,828911,Oogie Boogie Central,M. Stephen Lukac,2003,2003-00-00,Medium Rare Books,<NA>,USA,0971116288,NaN,NaN,False,False,Unknown,Unknown,0,0,False,False
77559,1828219,The Haunting of Lily Frost,Nova Weetman,2014,2014-04-00,University of Queensland Press,<NA>,NaN,9780702250156.0,NaN,"['ghosts', 'young adult contemporary fantasy',...",False,False,04,Unknown,0,0,False,False
113241,2634865,The Smalls,J. S. Frankel,2019,2019-10-04,Devine Destinies,<NA>,"Toronto, Canada",9781487425104.0,NaN,['science fiction'],False,False,10,Unknown,0,0,False,False
125510,3610240,Snow White Unleashed,Cate Farren,2021,2021-11-28,Cate Farren,<NA>,NaN,9798775297510.0,NaN,NaN,False,False,11,Unknown,0,0,False,False
91358,2101689,Freedom's Prisoners,Katrina Mountfort,2016,2016-11-14,Elsewhen Press,<NA>,"Leeds, Yorkshire, England, UK",9781911409021.0,NaN,"['dystopia', 'young-adult sf']",False,False,11,Unknown,0,0,False,False
56368,1104108,Shadow from the Past,E. A. Rappaport,2010,2010-01-00,Owl King Publishing,<NA>,NaN,9780978939342,NaN,['fantasy'],False,False,01,Unknown,0,0,False,False
36243,2122257,The Burning of Her Sin,Patty G. Henderson,2004,2004-11-30,Bella Books,<NA>,"Tampa, Florida, USA",1594930341,NaN,NaN,False,False,11,Unknown,0,0,False,False
102575,3322226,Prophecy Awakened,Tamar Sloan,2018,2018-06-07,Jess Connors Publishing,<NA>,NaN,9780648092339.0,NaN,NaN,False,False,06,Unknown,0,0,False,False
123648,3409493,"When God Was Stolen, Book Two",Cary Osborne,2020,2020-05-26,Gordian Knot Books,<NA>,NaN,NaN,NaN,NaN,False,False,05,Unknown,0,0,False,False
115600,2706426,Lord of the Deep,Mark Albany,2019,2019-10-28,Mark Albany,<NA>,NaN,NaN,NaN,NaN,False,False,10,Unknown,0,0,False,False
100300,2532228,Basket Bear,Amy Star,2017,2017-01-16,Amy Star,<NA>,NaN,9781540834836.0,NaN,NaN,False,False,01,Unknown,0,0,False,False
111693,2550172,The Silent Songbirds,Anne Booth,2019,2019-06-06,Oxford University Press,<NA>,NaN,9780192766274.0,NaN,['juvenile fantasy'],False,False,06,Unknown,0,0,False,False
60734,1349548,Those Left Behind,Joseph Freeman,2011,2011-10-31,Castringham Hall,<NA>,NaN,9780957034808,"Thirty years ago, five children were preyed up...",NaN,False,False,10,Unknown,0,0,False,False
77071,1872031,Scorched,Erica Hayes,2014,2014-05-22,HarperImpulse,<NA>,"Melbourne, Victoria, Australia",9780007594610.0,NaN,"['superpowers', 'telekinesis', 'urban fantasy']",False,False,05,Unknown,0,0,False,False
52666,3531465,The Strange Case of Origami Yoda,Tom Angleberger,2010,2010-03-01,Amulet Books,1971,"Staunton, Virginia, USA",9780810984257,NaN,NaN,False,False,03,39,0,0,False,False
61019,1346565,Cryptic,D. A. Chaney,2011,2011-09-14,May December Publications,<NA>,NaN,9781936730124,NaN,NaN,False,False,09,Unknown,0,0,False,False
148468,3534252,Sky Shielder,Lindsay Buroker,2025,2025-10-28,Lindsay Buroker,1977,"Seattle, Washington, USA",9781951367503.0,NaN,NaN,False,False,10,48,0,0,False,False
117405,2619067,Dragon Clan,Linda McNabb,2019,2019-09-08,Linda McNabb,1963,"Rutland, England, UK",9781691919819.0,NaN,['fantasy'],False,False,09,56,0,0,False,False
145297,3303418,"The Way of the Quantamancer, Pt. 1",A. R. McNevin,2024,2024-03-18,A. R. McNevin,<NA>,NaN,9798872055662.0,NaN,NaN,False,False,03,Unknown,0,0,False,False
74793,1665512,Rock & Roll!,Dotti Enderle,2014,2014-01-01,Magic Wagon,1954,"Killeen, Texas, USA",9781624020032.0,NaN,"['ghosts', 'juvenile fantasy']",False,False,01,60,0,0,False,False
145437,3349953,Frankenstein,"Mary Shelley, unknown",2024,2024-10-01,Oxford University Press,1797,"Somers Town, St Pancras, Middlesex, England, K...",9781382055475.0,NaN,NaN,False,False,10,227,0,0,False,False
78191,1760554,Sacrifice,Brigid Kemmerer,2014,2014-09-30,K Teen / Kensington Publishing Corp.,1978,"Omaha, Nebraska, USA",9780758294395.0,"Earth, Fire. Air. Water. One misstep and they ...","['young-adult fantasy', 'Juvenile Fiction', 'Y...",False,False,09,36,0,0,False,False
2983,868153,Dam of Death,Jack Pearl,1967,1967-00-00,Whitman Publishing Company,1923,"Richmond Hill, New York, USA",NaN,NaN,NaN,False,False,Unknown,44,0,0,False,False
129469,2838264,Vicarious,Rhett C. Bruno,2021,2021-04-13,Aethon Books,<NA>,NaN,9781949890723.0,NaN,['science fiction'],False,False,04,Unknown,0,0,False,False
110888,2469372,A Labyrinth of Scions and Sorcery,Curtis Craddock,2019,2019-01-22,Tor,<NA>,NaN,9780765389626.0,A Labyrinth of Scions and Sorcery is the maste...,"['fantasy', 'Fantasy', 'Adventure', 'Fiction',...",False,False,01,Unknown,0,0,False,False
123403,3330062,Enter Oblivion,John Corwin,2020,2020-05-03,Raven House,<NA>,NaN,9781942453208.0,NaN,NaN,False,False,05,Unknown,0,0,False,False
32236,818513,Warriors of the Raven,Alan Gibbons,2001,2001-04-00,Dolphin / Orion Children's Books,1953,"Warrington, Lancashire, England, UK",1842550012,NaN,NaN,False,False,04,48,0,0,False,False
32430,372071,Book of Shadows,Cate Tiernan,2001,2001-01-00,Speak / Penguin Books (US),1961,"New Orleans, Louisiana, USA",0142409863,"Morgan and her best friend, Bree, are introduc...","['witches', 'young-adult fantasy', 'Fantasy', ...",False,False,01,40,0,0,False,False
89194,1977641,Lightning Sealed,Lila Felix,2016,2016-02-01,Clean Teen Publishing,<NA>,NaN,9781634221825.0,NaN,['young-adult fantasy'],False,False,02,Unknown,0,0,False,False
107844,2651569,Crimson Horizon,"Heather Renee, Lela Grayce",2018,2018-12-06,Heather Renee & Lela Grayce,<NA>,NaN,9781729182673.0,NaN,NaN,False,False,12,Unknown,0,0,False,False
25647,13516,Wyrd Sisters - the Play,"Stephen Briggs, Terry Pratchett",1996,1996-00-00,Corgi,1948,"Beaconsfield, Buckinghamshire, England, UK",0552144304,"A king cruelly murdered, his throne usurped by...","['Fantasy', 'Fiction', 'Science fiction', 'Gen...",False,False,Unknown,48,0,0,False,False
27630,27366,Behind Enemy Lines,John Vornholt,1998,1998-11-00,Pocket Books,1951,"Marion, Ohio, USA",067102499X,NaN,[],False,False,11,47,0,0,False,False
72128,1602013,Nevermore,David Niall Wilson,2013,2013-04-22,Crossroad Press,1959,"Flora, Illinois, USA",9781937530341.0,NaN,['fantasy'],False,False,04,54,0,0,False,False
11561,1469546,C.L.U.T.Z.,Marilyn Z. Wilkes,1982,1982-05-00,The Dial Press,<NA>,NaN,0803711573,NaN,NaN,False,False,05,Unknown,0,0,False,False
125544,3309090,Dreadnaught,Anthony J. Melchiorri,2021,2021-10-19,Firehawk Press,<NA>,NaN,9798750869244.0,NaN,NaN,False,False,10,Unknown,0,0,False,False
5235,4919,Black Legion of Callisto,Lin Carter,1972,1972-12-00,Orbit / Futura,1930,"St. Petersburg, Florida, USA",0860078256,NaN,NaN,False,False,12,42,0,0,False,False

In [11]:
## Add Author Birthplace by country
replace_dict = {'Austria':['Austria-Hungary','Austro-Hungarian Empire','Austria'],
               'Russia':['Russian Empire','Russia','USSR','Soviet'],
               'Germany':['German Empire','Reich','Confederation','Germany','Prussia'],
               'Nigeria':['Nigeria'],
               'India':['INdia','India'],
               'Peru':['Perú','Peru'],
               'Ceylon':['Ceylon'],
               'Papua New Guinea':['Netherlands New Guinea'],
               'Hong Kong':['Territory','Kong','Hong Kong','Komg'],
               'Dominican Republic':['Dominican Republic'],
               'Bailiwack of Jersey':['Balliwack of Jersey','Bailiwick of Jersey'],
               'Trinidad and Tobago':['Tobago','Trinidad'],
               'UK': ['Yorkshire','Wales','England','United Kingdom','UK','Scotland','Northern Ireland','Guernsey','Britain'],
               'Australia':['Sydney','New South Wales','Australia','Queensland','Victoria','Gold Coast'],
               'USA':['Philadelphia','MO','PA','WA','PR','Baltimore','USA','US Virgin Islands','Puerto Rico'],
               'Panama':['Canal Zone','Panama'],
               'Sri Lanka': ['Lanka'],
               'New Zealand':['Zealand','NZ'],
               'East Indies' :['East Indies'],
                'West Indies' :['West Indies','Antilles','Dominica'],
                'El Salvador' :['El Salvador'],
                'South Africa' :['Cape Colony','Pretoria','Port Elizabeth','South Africa','Orange Free'],
                'United Arab Emirates' :['United Arab Emirates'],
                'Sierra Leone' :['Sierra Leone'],
                'Canada': ['British North America','Canada','Alberta'],
                'Guyana':['Guyana','British Guiana'],
                'Cayman Islands': ['Cayman'],
                'Marshall Islands':['Marshall'],
                'Thailand': ['Thailand','Siam'],
                'Malaysia':['Malaya','Malaysia'],
                'Philipines':['Philipines','Philippine Islands'],
                'Ireland' : ['Ireland','Irish'],
                'Turkey':['Turkey','Ottoman Empire'],
                'Rhodesia':['Rhodesia'],
                'Bermuda':['Bermuda'],
                'Kenya':['Kenya'],
                'Jamaica':['Jamaica'],
                'Sweden':['Sweden','Swedish'],
                'Singapore':['Singapore'],
                'Nyasaland':['Nyasaland'],
                'Palestine':['Palestine'],
                'Fiji':['Fiji'],
                'Holy Roman Empire':['Holy Roman Empire'],
                'Myanmar':['Burma','Myanmar'],
                'Malta':['Malta'],
                'Czech Republic':['Czech'],
                'Rwanda':['Rwanda','Portugese West Africa','Kamundongo']
}

def replace_author_birthplace_country(x):
    if pd.isna(x):
        return 'Unknown'
    for country, birthplace in replace_dict.items():
        if any(word in x for word in birthplace):
            return country
    if x not in replace_dict.items():
        return x.strip().split()[-1]
    return x

In [12]:
books = books.assign(author_birthplace_country=books['author_birthplace'].apply(replace_author_birthplace_country))
books.sample(15)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before,author_birthplace_country
84259,1862200,Hostage,"Sherwood Smith, Rachel Manija Brown",2015,2015-01-06,Book View Café,1951,"Glendale, California, USA",9781611384734.0,NaN,[],False,False,01,64,0,0,False,False,USA
47638,714945,Grimspace,Ann Aguirre,2008,2008-02-26,Ace Books,1970,USA,9780441015993,"As the carrier of a rare gene, Sirantha Jax ha...","['adventure', 'ofearna-2008', 'ofearna-ebooks'...",False,False,02,38,0,0,False,False,USA
29292,20024,The Stainless Steel Rat Joins the Circus,Harry Harrison,1999,1999-11-00,Tor,1925,"Stamford, Connecticut, USA",0312869347,When you are the richest man in the Universe a...,"['circus', 'science fiction', 'thief', 'Scienc...",False,False,11,74,2,2,True,True,USA
37849,916020,Attack of the Bounty Hunters,Steven Gordon,2004,2004-00-00,Clifford Croft Press,<NA>,NaN,0974965200,NaN,NaN,False,False,Unknown,Unknown,0,0,False,False,Unknown
63547,1523606,Flora's Fury,Ysabeau S. Wilce,2012,2012-05-08,Harcourt / Houghton Mifflin Harcourt,<NA>,"California, USA",9780152054090,_Publisher:_ Determined to find her true mothe...,['young-adult fantasy'],False,False,05,Unknown,0,0,False,False,USA
982,1528063,Providence Island,Jacquetta Hawkes,1959,1959-04-00,Random House,1910,"Cambridge, Cambridgeshire, England, UK",NaN,"Lost race novel, set on a Pacific Island.\n\n",['lost race'],False,False,04,49,0,0,False,False,UK
29139,19503,Foundation's Triumph,David Brin,1999,1999-05-00,HarperPrism,1950,"Glendale, California, USA",0061052418,The Second Foundation Trilogy begins with Greg...,"['cyborgs', 'Earth', 'interstellar travel', 'p...",False,False,05,49,6,8,True,True,USA
80305,11380,The Interloper,John Russell Fearn,2015,2015-03-31,Gateway / Orion,1908,"Worsley, Lancashire, England, UK",9781473210318.0,NaN,"['armaments baron', 'interplanetary relations']",False,False,03,107,0,0,False,False,UK
139124,3149746,Rebel Squad,"Michael Anderle, Martha Carr",2023,2023-03-06,LMBPN Publishing,<NA>,NaN,9798885419550.0,NaN,NaN,False,False,03,Unknown,0,0,False,False,Unknown
137150,3088691,A Consuming Fire,Laura E. Weymouth,2022,2022-11-22,Margaret K. McElderry Books,<NA>,"Ontario, Canada",9781665902700.0,NaN,['young-adult fantasy'],False,False,11,Unknown,0,0,False,False,Canada
23946,3377169,The Net,Leonore Fleischer,1995,1995-00-00,Boxtree,1932,NaN,0752201387,NaN,[],False,False,Unknown,63,0,0,False,False,Unknown
105475,2328103,Love Beyond Flames,Rebecca Royce,2018,2018-02-10,Rebecca Royce,<NA>,NaN,NaN,NaN,NaN,False,False,02,Unknown,0,0,False,False,Unknown
85537,2037994,Dead in the Water,Hailey Edwards,2015,2015-12-28,Hailey Edwards,<NA>,NaN,9781522951407.0,"Gemini, Book 1 Camille Ellis is the Earthen Co...",['urban fantasy'],False,False,12,Unknown,0,0,False,False,Unknown
114981,2666920,Overlook,"Jon Mollison, Thomas Plutarch",2019,2019-11-22,Silver Empire,<NA>,NaN,9781949891935.0,NaN,['superhero'],False,False,11,Unknown,0,0,False,False,Unknown
80548,2246062,The Mothers,Mike Jones (I),2015,2015-08-00,Simon & Schuster (Australia),<NA>,NaN,9781925030938.0,NaN,['horror'],False,False,08,Unknown,0,0,False,False,Unknown

In [13]:
## Author Birthplace by continent
continent_dict = {
'Africa' : ['Africa','Zambia','Libya','Sudan','Ethiopia','Madagascar','Morocco','Sudan','Namibia','Niger','Botswana','Liberia','Tunisia','Mauritius',
          'Nyasaland','Sierra Leone','Guinea','Tanzania','Zimbabwe','Uganda','Ghana','Egypt','Kenya','Rwanda','Nigeria','Rhodesia','South Africa',
          ],
'Europe' : ['Cyprus','Marino','Macedonia','Latvia','Holy Roman Empire','Luxembourg','Gibraltar','Bulgaria','Ukraine','Serbia','Bailiwack of Jersey',
          'Denmark','Norway','Iceland','Czech Republic','Greece','Hungary','Finland','Spain','Romania','Malta','Belgium','Poland','Portugal',
          'Switzerland','Yugoslavia','Austria','Sweden','Italy','Netherlands','France','Russia','Germany','Ireland','UK'],
'South America' : ['Suriname','Uruguay','Bolivia','Colombia','Guyana','Chile','Ecuador','Peru','Argentina','Brazil','Venezuela'],
'Central/North America' : ['USA','Honduras','Bahamas','Guatemala','Barbados','Cayman Islands','Croatia','Grenada','Panama','Jamaica','Bermuda',
                         'Haiti','Trinidad and Tobago','Cuba','West Indies','Mexico','Dominican Republic','Canada'],
'Asia' : ['Iraq','East Indies','Myanmar','Philippines','Brunei','Macau','Kuwait','Nepal','United Arab Emirates','Bahrain','Vietnam','Laos','Arabia',
        'Pakistan','Palestine','Sri Lanka','Bangladesh','Persia','Turkey','Lebanon','Ceylon','Korea','Thailand','Indonesia','Taiwan','Iran',
        'Singapore','Malaysia','Philippines','Hong Kong','China','Israel','Japan','India'],
'Oceania' : ['Australia','New Zealand','Samoa','Marshall Islands','Papua New Guinea','Fiji']
}

def replace_author_birthplace_continent(x):
    if pd.isna(x):
        return 'Unknown'
    for country, birthplace in continent_dict.items():
        if any(word in x for word in birthplace):
            return country
    if x not in replace_dict.items():
        return x.strip().split()[-1]
    return x

In [14]:
books = books.assign(author_birthplace_continent=books['author_birthplace'].apply(replace_author_birthplace_continent))
books.sample(15)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,...,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before,author_birthplace_country,author_birthplace_continent
12498,987037,Time Trap,Jean M. Favors,1984,1984-00-00,Parachute Press / Scholastic,1938,NaN,059033168X,NaN,...,False,False,Unknown,46,0,0,False,False,Unknown,Unknown
83931,1797758,Unbreakable,W. C. Bauers,2015,2015-01-13,Tor,<NA>,NaN,9780765375421.0,NaN,...,False,False,01,Unknown,0,0,False,False,Unknown,Unknown
137800,3164673,Trapped in the Dark,Jada Fisher,2023,2023-03-28,Fairfield Publishing,<NA>,NaN,NaN,NaN,...,False,False,03,Unknown,0,0,False,False,Unknown,Unknown
67241,1404424,Embrace of the Damned,Anya Bast,2012,2012-05-01,Berkley Sensation,1972,"Minnesota, USA",9780425247969.0,NaN,...,False,False,05,40,0,0,False,False,USA,Central/North America
474,21806,The Domes of Mars,Patrick Moore,1956,1956-00-00,Burke,1923,"Pinner, Middlesex, England, UK",NaN,NaN,...,False,False,Unknown,33,0,0,False,False,UK,Europe
107549,2442033,Shadowblood Heir,J. S. Morin,2018,2018-02-20,Magical Scrivener Press,1977,"New Hampshire, USA",9781942642220.0,NaN,...,False,False,02,41,0,0,False,False,USA,Central/North America
31383,21831,Fortune's Stroke,"David Drake, Eric Flint",2000,2000-06-00,Baen Books,1945,"Dubuque, Iowa, USA",0671319981,EVIL FROM BEYOND TIME RULES THE GREATEST EMPIR...,...,False,False,06,55,0,0,False,False,USA,Central/North America
93060,2049054,Native Wind,A. M. Burns,2016,2016-07-19,DSP Publications,<NA>,NaN,9781634765527.0,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
134231,2993948,Lover Arisen,J. R. Ward,2022,2022-04-05,Gallery Books,1969,"Boston, Massachusetts, USA",9781982179991.0,"Possessed by the demon Devina, Balthazar is on...",...,False,False,04,53,0,0,False,False,USA,Central/North America
91291,2174172,Reckoning in the Void,J. T. Williams,2016,2016-01-14,J. T. Williams,<NA>,NaN,NaN,NaN,...,False,False,01,Unknown,0,0,False,False,Unknown,Unknown
106376,2458129,The White Morning: A Novel of the Power of the...,Gertrude Atherton,2018,2018-09-26,Frederick A. Stokes Company,1857,"San Francisco, California, USA",9781633916395.0,"\n""... set in the very _Near Future_ , Germa...",...,False,False,09,161,0,0,False,False,USA,Central/North America
10816,3337,Sun Dogs,Mark J. McGarry,1981,1981-02-00,Signet / New American Library,1958,"Albany, New York, USA",0451096207,NaN,...,False,False,02,23,0,0,False,False,USA,Central/North America
30974,365291,Independence Day,Peter Darvill-Evans,2000,2000-10-00,BBC Worldwide,1954,"Buckinghamshire, England, UK",056353804X,NaN,...,False,False,10,46,0,0,False,False,UK,Europe
30352,21342,Tribulations,J. Michael Straczynski,2000,2000-08-00,DarkTales Publications,1954,"Paterson, New Jersey, USA",1930997035,ibooks is proud to present a little-seen thril...,...,False,False,08,46,0,0,False,False,USA,Central/North America
78833,1748883,Taste of Torment,Suzanne Wright,2014,2014-01-30,Suzanne Wright,<NA>,"England, UK",9781495311918.0,It’s been five months since vampire Sam Parker...,...,False,False,01,Unknown,0,0,False,False,UK,Europe

In [ ]:
books.reset_index()
books.to_csv("data_with_author_and_awards.csv", index = False)