In [238]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [239]:
locus = pd.read_csv('locus_nominees.csv')
locus.head()

                       title             author  year
0                  Ringworld        Larry Niven  1971
1             Tower of Glass  Robert Silverberg  1971
2  The Year of the Quiet Sun      Wilson Tucker  1971
3             And Chaos Died        Joanna Russ  1971
4      Downward to the Earth  Robert Silverberg  1971

In [240]:
hugo = pd.read_csv('hugo_nominees.csv')
hugo.head()

                    title                    author  year
0      The Demolished Man             Alfred Bester  1953
1  They'd Rather Be Right  Mark Clifton&Frank Riley  1955
2             Double Star        Robert A. Heinlein  1956
3         “Call Him Dead”        Eric Frank Russell  1956
4     The End of Eternity              Isaac Asimov  1956

In [241]:
books = pd.read_csv('isfdb-hardcover-combined.csv')
books.head()

,Unnamed: 0,title_id,author,release_year,release_date,author_age_at_release,author_birthplace,isbn,first_publisher,book_synopsis,tags,title
0,0,1,Geoff Ryman,1985,1985-05-00,34.0,Canada,0044407777,Unwin Paperbacks,<b>From the back cover of the Bantam paperback...,"['bsfa award for best novel finalist', 'fantas...",The Warrior Who Carried Life
1,1,4,Ben Bova,1973,1973-03-00,41.0,"Philadelphia, Pennsylvania, USA",0727817760,Severn House,NaN,"['science fiction', 'young-adult sf']",The Winds of Altair
2,2,6,Ben Bova,1993,1993-09-00,61.0,"Philadelphia, Pennsylvania, USA",0812511654,Tor,NaN,"['science fiction', 'Fantasy', 'Adventure', 'F...",Empire Builders
3,3,7,Ben Bova,1985,1985-10-00,53.0,"Philadelphia, Pennsylvania, USA",0812534891,Tor,NaN,['science fiction'],Privateers
4,4,8,Ben Bova,1990,1990-04-00,58.0,"Philadelphia, Pennsylvania, USA",0312932154,Tor,A courageous astronaut braves the awesome powe...,"['nanotechnology', 'science fiction', 'Fantasy...",Star Brothers

In [ ]:
hugo.title = hugo.title.apply(lambda x : x.lstrip('“').rstrip('”'))
hugo.title = hugo.title.apply(lambda x : x.lower())
hugo

                      title                    author  year
0        The Demolished Man             Alfred Bester  1953
1    They'd Rather Be Right  Mark Clifton&Frank Riley  1955
2               Double Star        Robert A. Heinlein  1956
3             Call Him Dead        Eric Frank Russell  1956
4       The End of Eternity              Isaac Asimov  1956
..                      ...                       ...   ...
360    A Drop of Corruption    Robert Jackson Bennett  2026
361         The Everlasting            Alix E. Harrow  2026
362        The Incandescent                Emily Tesh  2026
363       The Raven Scholar           Antonia Hodgson  2026
364                  Shroud        Adrian Tchaikovsky  2026

[365 rows x 3 columns]

In [243]:
locus.title = locus.title.apply(lambda x : x.strip('“').strip('”'))
locus.head()

                       title             author  year
0                  Ringworld        Larry Niven  1971
1             Tower of Glass  Robert Silverberg  1971
2  The Year of the Quiet Sun      Wilson Tucker  1971
3             And Chaos Died        Joanna Russ  1971
4      Downward to the Earth  Robert Silverberg  1971

In [244]:
hugo_mask = books.author.isin(hugo.author) & books.title.isin(hugo.title)
locus_mask = books.author.isin(locus.author) & books.title.isin(locus.title)

In [245]:
books['hugo'] = hugo_mask
books['locus'] = locus_mask

In [246]:
for title in hugo.title:
    if len(books.loc[books.title == title]) == 0:
        print(title, ':', hugo[hugo.title == title].author.iloc[0])

Call Him Dead : Eric Frank Russell
Have Space Suit -- Will Travel : Robert A. Heinlein
Sylva : Vercors
Dune World : Frank Herbert
The Dispossessed : Ursula K. Le Guin
Flow My Tears :  the Policeman Said
The Inverted World : Christopher Priest
The Mote In God's Eye : Larry Niven&Jerry Pournelle
Little :  Big
Beggars In Spain : Nancy Kress
Beggars and Choosers : Nancy Kress
To Say Nothing of the Dog : Connie Willis
Harry Potter and the Prisoner of Azkaban : J. K. Rowling
Harry Potter and the Goblet of Fire : J. K. Rowling
Eifelheim : Michael Flynn
His Majesty's Dragon : Naomi Novik
Blackout/All Clear : Connie Willis
The Wheel of Time : Robert Jordan&Brandon Sanderson
The Three-Body Problem : Cixin Liu
The Goblin Emperor : Katherine Addison
Death's End : Cixin Liu
The Galaxy :  and the Ground Within
Light From Uncommon Stars : Ryka Aoki
Nettle & Bone : T. Kingfisher
Legends & Lattes : Travis Baldree
The Adventures of Amina al-Sirafi : Shannon Chakraborty
Someone You Can Build a Nest In : John Wiswell
A Sorceress Comes to Call : T. Kingfisher

In [247]:
for title in locus.title:
    if len(books[books.title == title]) == 0:
        print(title, ":", locus[locus.title == title].author.iloc[0])

The Doomsday Gene : John Boyd
The Dispossessed : Ursula K. Le Guin
Flow My Tears :  the Policeman Said
The Unsleeping Eye : D. G. Compton
The Inverted World : Christopher Priest
The Domains of Koryphon : Jack Vance
The Computer Connection(serial title “The Indian Giver“) : Alfred Bester
Blake's Progress : Ray Nelson
Warriors of Dawn : M. A. Foster
Illuminatus! : Robert Shea&Robert Anton Wilson
All My Sins Remembered : Joe Haldeman
The Silmarillion : J. R. R. Tolkien
The Chronicles of Thomas Covenant the Unbeliever : Stephen R. Donaldson
Silver on the Tree : Susan Cooper
The Stars In Shroud : Gregory Benford
The Outcasts of Heaven's Belt : Joan D. Vinge
Gloriana : Michael Moorcock
Stardance II : Spider Robinson&Jeanne Robinson
 “The Eye of the Heron : Ursula K. Le Guin
Masters of Solitude : Marvin Kaye&Parke Godwin
Catacomb Years : Michael Bishop
Tales of Nevèrÿon : Samuel R. Delany
Golem100 : Alfred Bester
Sabella : Tanith Lee
King David's Spaceship : Jerry Pournelle
Little :  Big
Lycanthia : Tanith Lee
Journey Behind the Wind : Patricia Wrightson
Roderick : John Sladek
Ogre :  Ogre
Oh Susannah! : Kate Wilhelm
Elfstones of Shannara : Terry Brooks
Welcome :  Chaos
Lyonesse : Jack Vance
Neveryóna : Samuel R. Delany
The Neverending Story : Michael Ende
'Ware Hawk! : Andre Norton
Stars In My Pocket Like Grains of Sand : Samuel R. Delany
 A Comedy of Justice : Robert A. Heinlein
Enchanter's End Game : David Eddings
The Businessman : Thomas M. Disch
Fire and Hemlock : Diana Wynne Jones
The Beggar Queen : Lloyd Alexander
The Cat Who Walks Through Walls : Robert A. Heinlein
The Book of Kells : R. A. MacAvoy
Lyonesse II: The Green Pearl : Jack Vance
Mulengro : Charles de Lint
Wizard of the Pigeons : Megan Lindholm
In Yana :  the Touch of Undying
Marianne :  the Magus
Santiago : Mike Resnick
Lear's Daughters : M. Bradley KelloggwithWilliam Rossow
Wizard of the Pigeons : Megan Lindholm
Magic Kingdom For Sale--Sold! : Terry Brooks
New York by Knight : Esther M. Friesner
The King of Ys: Roma Mater : Poul Anderson&Karen Anderson
The Unconquered Country : Geoff Ryman
Yarrow : Charles de Lint
The Secret Ascension : Michael Bishop
Code Blue — Emergency! : James White
The Awakeners:Northshore; Southshore : Sheri S. Tepper
�gypt : John Crowley
The Dark Tower II: The Drawing of the Three : Stephen King
Orphan of Creation : Roger MacBride Allen
Sister Light :  Sister Dark
The Reindeer People : Megan Lindholm
Buying Time(UK title:The Long Habit of Living) : Joe Haldeman
The Queen of Springtime(US title:The New Springtime) : Robert Silverberg
Marianne :  the Magus
Gate of Darkness :  Circle of Light
Stranger in a Strange Land [Expanded Edition](original uncut edition) : Robert A. Heinlein
Clarke County :  Space
In the Country of the Blind : Michael F. Flynn
Agviq : Michael Armstrong
 The Last Book of Earthsea : Ursula K. Le Guin
Good Omens : Terry Pratchett&Neil Gaiman
Ghostwood : Charles de Lint
King of Morning :  Queen of Day
Cloven Hooves : Megan Lindholm
Hearts :  Hands and Voices
�stival Tide : Elizabeth Hand
Was : Geoff Ryman
The Magicians of Night(UK title:Magicians of the Night) : Barbara Hambly
The Gypsy : Steven Brust&Megan Lindholm
Winter of the Wolf(US title:The Belly of the Wolf) : R. A. MacAvoy
The Wizard's Apprentice : S. P. Somtow
Dragon Star Book III: Skybowl : Melanie Rawn
Beggars and Choosers : Nancy Kress
Worldwar: In the Balance : Harry Turtledove
Cald� of the Long Sun : Gene Wolfe
Necroville(US title:Terminal Caf�) : Ian McDonald
Half the Day is Night : Maureen F. McHugh
Memory & Dream : Charles de Lint
Summer King :  Winter Fool
Exiles 1: The Ruins of Ambrai : Melanie Rawn
Chaga(US title:Evolution's Shore) : Ian McDonald
Worldwar: Tilting the Balance : Harry Turtledove
Waking the Moon(revised) : Elizabeth Hand
The Silent Strength of Stones : Nina Kiriki Hoffman
Otherland: City of Golden Shadow : Tad Williams
Nadya: The Wolf Chronicles : Pat Murphy
The Golden Compass(UK title:Northern Lights) : Philip Pullman
/ Slant : Greg Bear
Einstein's Bridge : John Cramer
The Dark Tower IV: Wizard and Glass : Stephen King
The Subtle Knife : Philip Pullman
Gate of Ivory :  Gate of Horn
To Say Nothing of the Dog : Connie Willis
Otherland: River of Blue Fire : Tad Williams
Dark Lord of Derkholm : Diana Wynne Jones
Harry Potter and the Philosopher's Stone(US title:Harry Potter and the Sorcerer's Stone) : J. K. Rowling
Time: Manifold 1(US title:Manifold: Time) : Stephen Baxter
Harry Potter and the Prisoner of Azkaban : J. K. Rowling
The Sub : Thomas M. Disch
Rhapsody : Elizabeth Haydon
Space: Manifold 2(US title:Manifold: Space) : Stephen Baxter
The Amber Spyglass : Philip Pullman
Ash: A Secret History : Mary Gentle
Daemonomania : John Crowley
White as Snow : Tanith Lee
Harry Potter and the Goblet of Fire : J. K. Rowling
Origin: Manifold 3 : Stephen Baxter
Metaplanetary : Tony Daniel
Whole Wide World : Paul McAuley
Otherland: Sea of Silver Light : Tad Williams
Lirael : Garth Nix
Bold as Love : Gwyneth Jones
The House in the High Woold : Jeffrey E. Barlough
The Golden Age: The Phoenix Exultant; The Golden Transcendence : John C. Wright
Succession: The Risen Empire; The Killing of Worlds : Scott Westerfeld
Felaheen: The Third Arabesk : Jon Courtenay Grimwood
The Dark Tower V: Wolves of the Calla : Stephen King
lost boy lost girl : Peter Straub
 The Confusion; The System of the World : Neal Stephenson
For Us :  the Living
The Fourth Circle : Zoran Zivkovic
Spondulix : Paul Di Filippo
The Wizard Knight : Gene Wolfe
The Dark Tower: Song of Susannah : Stephen King
One King :  One Soldier
The Carpet Makers : Andreas Eschbach
Someone Comes to Town :  Someone Leaves Town
Eifelheim : Michael Flynn
Ilario: The Lion's Eye : Mary Gentle
Temeraire: His Majesty's Dragon/Throne of Jade/Black Powder War : Naomi Novik
Black Man(US title:Thirteen) : Richard Morgan
Engineer Trilogy: Devices and Desires/Evil for Evil/The Escapement : K. J. Parker
 In the Cities of Coin and Spice : Catherynne M. Valente
Blood Engines : T. A. Pratt
The Quiet War : Paul McAuley
The January Dancer : Michael Flynn
The Company : K. J. Parker
Shadowbridge/Lord Tophet : Gregory Frost
Memoirs of a Master Forger : William Heaney
Gardens of the Sun : Paul McAuley
Buyout : Alexander C. Irvine
Cloud & Ashes: Three Winter's Tales : Greer Gilman
Spell Games : T. A. Pratt
Dragon in Chains : Daniel Fox
Blackout/All Clear : Connie Willis
The Thousand Autumns of Jacob de Zoet : David Mitchell
The Folding Knife : K. J. Parker
Jade Man's Skin : Daniel Fox
Caliban's War : James S. A. Corey
Fate of Worlds : Larry Niven&Edward M. Lerner
In the Mouth of the Whale : Paul McAuley
Sharps : K. J. Parker
Abaddon's Gate : James S. A. Corey
ID: The Second Machine Dynasty : Madeline Ashby
Evening's Empires : Paul McAuley
The Cusanus Game : Wolfgang Jeschke
Blood Oranges : Kathleen Tierney
Anno Dracula 1976-1991: Johnny Alucard : Kim Newman
The Three-Body Problem : Cixin Liu
Annihilation/Authority/Acceptance : Jeff VanderMeer
Cibola Burn : James S. A. Corey
The Memory of Sky : Robert Reed
B�te : Adam Roberts
The Goblin Emperor : Katherine Addison
Resurrections : Roz Kaveney
Death's End : Cixin Liu
Babylon's Ashes : James S. A. Corey
The Last Days of New Paris : China Mi�ville
Raven Strategem : Yoon Ha Lee
The Wonder Engine : T. Kingfisher
Ahab's Return : Jeffrey Ford
The Rosewater Insurrection/The Rosewater Redemption : Tade Thompson
War of the Maps : Paul McAuley
The Angel of the Crows : Katherine Addison
The Galaxy :  and the Ground Within
Leviathan Falls : James S. A. Corey
The Witness for the Dead : Katherine Addison
Paladin's Strength : T. Kingfisher
No Gods :  No Monsters
Nettle & Bone : T. Kingfisher
The Grief of Stones : Katherine Addison
Paladin's Faith : T. Kingfisher
To Shape a Dragon's Breath : Moniquill Blackgoose
My Mother's Keeper : Tim Powers
The Mercy of Gods : James S. A. Corey
A Sorceress Comes to Call : T. Kingfisher
Slow Gods : Claire North
Where the Axe is Buried : Ray Nayler
Hemlock & Silver : T. Kingfisher
The Tomb of Dragons : Katherine Addison

In [248]:
print(books.iloc[896])

Unnamed: 0                                                             896
title_id                                                               994
author                                                       Roger Zelazny
release_year                                                          1973
release_date                                                    1973-00-00
author_age_at_release                                                 36.0
author_birthplace                                        Euclid, Ohio, USA
isbn                                                            0413409805
first_publisher                                                    Methuen
book_synopsis            <b>From the back cover of the DAW first printi...
tags                                                                   NaN
title                                                    To Die in Italbar
hugo                                                                 False
locus                                                                 True
Name: 896, dtype: object