In [1]:
import numpy as np
import csv
import pandas as pd
from itertools import islice
import json
import matplotlib.pyplot as plt
pd.set_option("display.max_rows", None)

In [2]:
books = pd.read_csv('../data/final_book_dataset_cleaned.csv', sep = '\t',
        dtype={
            'author_birthyear' : 'Int64',
            'title_id' : 'Int64',
            'isbn' : 'str'
        }
    )

In [3]:
books.head(5)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus
0,9372,The Long Loud Silence,Wilson Tucker,1954,1954-00-00,Dell,1914,"Deer Creek, Illinois, USA",0899683754,Publisher's description: Tomorrow's war -- the...,"['Anatomy of Wonder 1 Core Collection', 'biolo...",False,False
1,2215181,Mrs. Candy Strikes It Rich,Robert Tallant,1954,1954-00-00,Doubleday,1909,"New Orleans, Louisiana, USA",NaN,NaN,NaN,False,False
2,1392436,Return to the Lost Planet,Angus MacVicar,1954,1954-00-00,Burke,1908,"Duror, Argyll, Scotland, UK",NaN,NaN,NaN,False,False
3,1112206,Rainbow on the Road,Esther Forbes,1954,1954-00-00,Houghton Mifflin,1891,"Westborough, Massachusetts, USA",NaN,NaN,NaN,False,False
4,1908,The Forgotten Planet,Murray Leinster,1954,1954-00-00,Ace Books,1896,"Norfolk, Virginia, USA",0881846163,"**From the first page of the Ace Double:** ""Na...","['insects', 'Librivox', 'Project Gutenberg', '...",False,False

In [4]:
## add month of publication column, 00 means only year is known
books['month_of_publication'] =books['release_date'].str[5:7].str.replace('00','Unknown')
books.sample(50)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus,month_of_publication
46493,1267871,Redcoats' Revenge: An Alternate History of the...,"Col. David Fitz-Enz, USA (ret.)",2008,2008-11-30,Potomac Books,<NA>,NaN,9781574889871,NaN,NaN,False,False,11
19229,3210312,"Armageddon, USA",Dan Schmidt,1991,1991-05-00,Bantam Falcon,<NA>,NaN,0553289462,NaN,NaN,False,False,05
25008,871628,The Cold People,Christopher Pike,1996,1996-02-00,Pocket Books,1954,"New York City, New York, USA",0671550640,NaN,NaN,False,False,02
74916,2891611,Child of Lies,Eric Kent Edstrom,2014,2014-08-29,Undermountain Books,<NA>,NaN,9780989901017.0,NaN,NaN,False,False,08
52735,1465521,The Sacred Band,"Janet Morris, Chris Morris",2010,2010-04-05,CreateSpace,1946,"Boston, Massachusetts, USA",9781451599862,NaN,['fantasy'],False,False,04
46960,926620,Vampires of Quentaris,Paul Collins,2008,2008-02-00,Lothian Children's Books / Hachette Australia,1954,"Canvey Island, Essex, England, UK",9780734409850,A synopsis can be found on the [Quentaris\nweb...,['juvenile fantasy'],False,False,02
26355,375751,A Device of Death,Christopher Bulis,1997,1997-02-00,Doctor Who Books,1956,"England, UK",0426205014,The crew of the TARDIS are scattered across th...,"['science fiction', 'English fiction', 'Scienc...",False,False,02
63872,2417011,2013 Evolution,Tosin Coker,2012,2012-12-23,N9neformation,<NA>,NaN,9780955748349,NaN,NaN,False,False,12
125012,3082935,Imitating a Fae Queen,Joanna Reeder,2021,2021-01-16,Reed It & Weep,<NA>,NaN,9798585916564.0,NaN,['young-adult fantasy'],False,False,01
46101,1274363,The Highest Seat Does Not Hold Two,David Williams (IV),2008,2008-09-01,Publication Consultants,<NA>,NaN,9781594330841,NaN,NaN,False,False,09
90448,2276473,Sacred Desires,Joanna Mazurkiewicz,2016,2016-07-19,Joanna Mazurkiewicz,<NA>,NaN,NaN,NaN,['fantasy'],False,False,07
30263,813197,The Private Memoirs and Confessions of a Justi...,James Hogg,2000,2000-08-01,Chanticleer Press,1770,"Ettrick, Selkirkshire, Scotland, Kingdom of Gr...",9781409935964,NaN,"['1001 Books You Must Read Before You Die', 'h...",False,False,08
80772,2646175,Final Death,Rose Garcia,2015,2015-04-22,Rose Garcia Books,<NA>,NaN,9781511850674.0,NaN,NaN,False,False,04
104594,2408433,My Arch-Enemy Is a Brain in a Jar,David Solomons,2018,2018-06-28,Nosy Crow,<NA>,NaN,9780857639912.0,NaN,"['juvenile sf', 'superhero']",False,False,06
29279,1280948,The Hand of Power,Cameron Dokey,1999,1999-01-00,Gold Key / Golden Books,1956,"Stockton, California, USA",0307248054,NaN,NaN,False,False,01
107625,2657463,Buffer Zone,Connie Suttle,2018,2018-04-28,SubtleDemon Publishing,<NA>,NaN,9781634780292.0,NaN,NaN,False,False,04
14346,960287,Mr. Majeika and the Music Teacher,Humphrey Carpenter,1986,1986-00-00,Viking Kestrel,1946,"Oxford, Oxfordshire, England, UK",0670807540,NaN,['juvenile fantasy'],False,False,Unknown
40400,921983,The Translation of Father Torturo,Brendan Connell,2005,2005-00-00,Prime Books,1970,"Santa Fe, New Mexico, USA",0809500434,NaN,NaN,False,False,Unknown
3814,3206728,Santa's Search,"Joseph Sciortino, Anthony Sciortino",1969,1969-00-00,Carlton Press,<NA>,NaN,NaN,NaN,NaN,False,False,Unknown
99382,2172947,The Para-Portage of Emily,Muffy Wilson,2017,2017-01-17,Bestselling Boxed Sets,<NA>,NaN,NaN,NaN,NaN,False,False,01
22319,1616331,Time Trek,Eric Scott,1994,1994-00-00,Longman Cheshire,1936,"England, UK",0582802717,NaN,"['teen science fiction', 'teen time travel', '...",False,False,Unknown
29811,1501862,Snow in Summer,Tess Farraday,1999,1999-02-01,Jove Books,<NA>,NaN,0515124753,NaN,[],False,False,02
5298,226991,Wildsmith,Ron Goulart,1972,1972-04-00,Ace Books,1933,"Berkeley, California, USA",NaN,NaN,NaN,False,False,04
82035,1875605,Masterminds,Kristine Kathryn Rusch,2015,2015-06-03,WMG Publishing,1960,"Oneonta, New York, USA",9781561466252.0,NaN,['science fiction'],False,False,06
19429,3227380,Sea Wolf,Duncan Long,1991,1991-03-00,HarperPaperbacks,1949,"Smith Center, Kansas, USA",0061001589,NaN,NaN,False,False,03
22027,3496296,The Slaughter King,Simon Whitechapel,1993,1993-00-00,Creation Books,<NA>,NaN,1871592607,NaN,['horror'],False,False,Unknown
120279,2776532,Omens,Suzanne Wright,2020,2020-10-20,Piatkus,<NA>,"England, UK",9780349416335.0,She’s the one thing he can’t control . . . Sin...,"['paranormal romance', 'Fantasy', 'Fiction', '...",False,False,10
86884,2765441,Advance to Contact,C. J. Carella,2016,2016-10-09,Fey Dreams Productions,<NA>,"New York, USA",9781539466444.0,NaN,['military sf'],False,False,10
8484,3213899,Bernard Into Battle,Margery Sharp,1978,1978-00-00,"Little, Brown",1905,"Salisbury, Wiltshire, England, UK",0316783269,NaN,[],False,False,Unknown
11752,15551,Haunting at Mill Lane,Ken Radford,1983,1983-00-00,Holiday House,<NA>,NaN,0823406768,NaN,"['young-adult ghost story', 'young-adult time-...",False,False,Unknown
82497,1919389,Money Troubles,Raymond Bean,2015,2015-08-01,Stone Arch Books,<NA>,NaN,9781496503695.0,NaN,['juvenile sf'],False,False,08
14683,8326,The Adventures of Christian Rosy Cross,David Foster,1986,1986-06-00,Penguin Books,1944,"Katoomba, New South Wales, Australia",0140077014,NaN,['Fiction'],False,False,06
137181,3065116,Full Immersion,Gemma Amor,2022,2022-09-13,Angry Robot,<NA>,NaN,9780857669810.0,"**FINALIST for the BSF Award for Best Horror, ...","['fantasy', 'horror', 'Fiction', 'Science Fict...",False,False,09
13666,15523,The Fairy Rebel,Lynne Reid Banks,1985,1985-00-00,Avon Camelot,1929,"London, England, UK",0380706504,NaN,"['fairies', 'young-adult fantasy']",False,False,Unknown
13775,3058414,4-D Funhouse,"Clayton Emery, Earl Wajenberg",1985,1985-09-00,TSR,1953,"Bethesda, Maryland, USA",0880382554,NaN,NaN,False,False,09
28205,21512,Chasm,Stephen Laws,1998,1998-07-00,Hodder & Stoughton,1952,"Newcastle upon Tyne, England, UK",0340666110,NaN,NaN,False,False,07
18911,14431,Sundered Soul: A Mythic Tale,Alfred Tella,1990,1990-07-00,Three Continents Press,1933,"Rhode Island, USA",0894106945,NaN,NaN,False,False,07
142104,3241339,Tower Ascendant,Wolfe Locke,2023,2023-07-12,Aethon Books,<NA>,NaN,9798852037060.0,NaN,NaN,False,False,07
8957,1043519,The Flintstones: The Mystery of the Missing Di...,uncredited,1979,1979-00-00,Ottenheimer,<NA>,NaN,NaN,NaN,NaN,False,False,Unknown
24203,32924,Whistling Dixie,Marcia Vaughan,1995,1995-00-00,HarperCollins,1951,"Tacoma, Washington, USA",0060210303,"Dixie Lee brings home an alligator, a snake, a...",[],False,False,Unknown
131340,2850994,Masters of Shadow,Thomas Parrott,2021,2021-04-13,Games Workshop,<NA>,NaN,9781789991659.0,NaN,NaN,False,False,04
49267,2181709,Printer's Devil,Stona Fitch,2009,2009-02-02,Two Ravens Press,<NA>,NaN,9781906120320,Two warring printers' guilds struggle to survi...,NaN,False,False,02
107381,2444315,Seeking Fate,Brenda Drake,2018,2018-08-24,Entangled Publishing,<NA>,NaN,9781726079235.0,NaN,['young-adult fantasy'],False,False,08
111407,2535514,The River Twice,Brenda W. Clough,2019,2019-01-15,Book View Café,1955,"Washington, District of Columbia, USA",9781611387643.0,NaN,['time travel'],False,False,01
40221,171075,The Spooky Trail,Keith Faulkner,2005,2005-08-01,Barron's Educational Series,<NA>,NaN,0764158341,NaN,NaN,False,False,08
8741,3046803,Tee-Bo the Incredible Talking Dog Leads the Wa...,Mary Burg Whitcomb,1978,1978-00-00,Golden Books,1909,"Berkeley, California, USA",0307215849,NaN,NaN,False,False,Unknown
103147,3562659,Black Holiday,J. M. Anjewierden,2018,2018-04-13,CJMA Press,<NA>,NaN,9798569636549.0,NaN,NaN,False,False,04
53756,1132311,Other,Karen Kincy,2010,2010-07-08,Flux,1986,"Redmond, Washington, USA",9780738719191,NaN,"['ofearna-ebooks', 'pooka', 'werewolf', 'young...",False,False,07
74611,1663598,The Descent,Alma Katsu,2014,2014-01-02,Arrow Books,1959,"Fairbanks, Alaska, USA",9780099559979.0,"The author of The Hunger delivers a “daring, s...","['immortality', 'paranormal romance']",False,False,01
30492,179716,Wind Spell,Mallory Loehr,2000,2000-06-00,Random House,<NA>,NaN,0679892176,NaN,NaN,False,False,06

In [5]:
## Add age of author at publication
books['Author_Age_at_Publication'] = 'Unknown'
books['Author_Age_at_Publication'] = books['Author_Age_at_Publication'].case_when([(books['author_birthyear'].isna() == False,books['release_year'] - books['author_birthyear'])])

In [6]:
books.sample(15)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus,month_of_publication,Author_Age_at_Publication
150851,3534971,Midnight Deception,Joline Pearce,2025,2025-07-17,Joline Pearce,<NA>,NaN,9798292933182.0,NaN,"['dark fantasy', 'fantasy romance', 'retold fa...",False,False,07,Unknown
97250,2235726,Pick the Plot,James Riley,2017,2017-09-26,Aladdin,1977,"Connecticut, USA",9781481461283.0,NaN,['juvenile fantasy'],False,False,09,40
147167,3428143,A Flame in the North,John Beresford,2024,2024-07-25,John Beresford,<NA>,NaN,9798334403666.0,NaN,NaN,False,False,07,Unknown
39958,185937,Breathe,Penni Russon,2005,2005-10-00,Greenwillow Books / HarperCollins,1974,"Tasmania, Australia",0060793937,NaN,"['teen fantasy', 'young-adult fantasy']",False,False,10,31
124746,2826290,Death Cultivator 2,Eden Hudson,2020,2020-11-24,Shadow Alley Press,<NA>,NaN,9798587422544.0,NaN,['fantasy'],False,False,11,Unknown
92833,2050521,The Hidden Letters of Velta B.,Gina Ochsner,2016,2016-07-26,Houghton Mifflin Harcourt,1970,USA,9780544253216.0,From a critically acclaimed fiction writer com...,"['Fiction', 'Fantasy', 'General']",False,False,07,46
82963,1903301,After Alice,Gregory Maguire,2015,2015-00-00,Playaway Digital Audio,1954,"Albany, New York, USA",9781467619400.0,NaN,['fantasy'],False,False,Unknown,61
12453,16465,Stitch in Snow,Anne McCaffrey,1984,1984-05-00,Tor,1926,"Cambridge, Massachusetts, USA",0812585623,"Dana Jane Lovell is a savvy, successful, attra...",['Fantasy'],False,False,05,58
91364,2101607,Waylaid,Susan Klaus,2016,2016-11-13,Clay Gulley Publishing,<NA>,"Sarasota, Florida, USA",9780997906400.0,NaN,['fantasy'],False,False,11,Unknown
130469,3059839,The Correction,John Hazen,2021,2021-06-02,Black Rose Writing,<NA>,NaN,9781684337620.0,NaN,['fantasy'],False,False,06,Unknown
132404,3323409,Chosen Angel,"V. P. Allasander, Tamar Sloan",2022,2022-04-07,Jess Connors Publishing,<NA>,NaN,9780645449822.0,NaN,NaN,False,False,04,Unknown
114234,2735376,An Ill Wind,Christine Pope,2019,2019-05-16,Dark Valentine Press,<NA>,"California, USA",9781946435231.0,"To find a dangerous grimoire, they’ll have to ...",[],False,False,05,Unknown
129482,2836821,Thrice Clawed,Angel Leya,2021,2021-01-07,Angel Leya,<NA>,NaN,9798596451900.0,NaN,NaN,False,False,01,Unknown
89658,2252497,Shadowmage,Terry Mancour,2016,2016-09-09,Terry Mancour,1968,"Flint, Michigan, USA",9781772309416.0,NaN,['fantasy'],False,False,09,48
38739,173080,Night Bites,Nina Bangs,2005,2005-03-06,Love Spell,<NA>,"San Antonio, Texas, USA",050552614X,When a darkly sensual vampire named Thrain Dav...,[],False,False,03,Unknown

In [7]:
## Add column with number of hugo or locus awards won prior to that date
books['Hugo_Awards_Previously']= books.groupby(['author'])['hugo'].cumsum()
books['Locus_Awards_Previously']= books.groupby(['author'])['locus'].cumsum()

In [16]:
display(books[books['author'] == 'Ada Palmer'])
#From the above example we see that .cumsum method counts the current row as well and is causing leakage.

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,...,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before,author_birthplace_country,author_birthplace_continent
90307,1989076,Too Like the Lightning,Ada Palmer,2016,2016-05-10,Tor,1981,"Washington, District of Columbia, USA",9780765378002.0,Mycroft Canner is a convict. For his crimes he...,...,True,False,05,35,1,0,True,False,USA,Central/North America
95067,2275090,The Will to Battle,Ada Palmer,2017,2017-12-19,Tor,1981,"Washington, District of Columbia, USA",9780765378040.0,"""The long years of near-utopia have come to an...",...,False,False,12,36,1,0,True,False,USA,Central/North America
100262,2131878,Seven Surrenders,Ada Palmer,2017,2017-02-00,Tor,1981,"Washington, District of Columbia, USA",9780765378026.0,"""It is a world in which near-instantaneous tra...",...,False,True,02,36,1,1,True,True,USA,Central/North America
128775,2923757,Perhaps the Stars,Ada Palmer,2021,2021-10-19,Ad Astra / Head of Zeus,1981,"Washington, District of Columbia, USA",9781786699602.0,The leaders of Hive nations—nations without fi...,...,False,False,10,40,1,1,True,True,USA,Central/North America

In [ ]:
##Once you run this cell the above bug will be fixed.

## Add column with number of hugo or locus awards won prior to that date
## We do this to ensure that hugo info about current year is not included
# cumsum includes the current year as well

books['Hugo_Awards_Previously'] = (
    books.groupby('author')['hugo'].cumsum() - books['hugo']
)
books['Locus_Awards_Previously'] = (
    books.groupby('author')['locus'].cumsum() - books['locus']
)

In [ ]:
display(books[books['author'] == 'Ada Palmer'])
#bug fixed

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,...,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before,author_birthplace_country,author_birthplace_continent
90307,1989076,Too Like the Lightning,Ada Palmer,2016,2016-05-10,Tor,1981,"Washington, District of Columbia, USA",9780765378002.0,Mycroft Canner is a convict. For his crimes he...,...,True,False,05,35,0,0,True,False,USA,Central/North America
95067,2275090,The Will to Battle,Ada Palmer,2017,2017-12-19,Tor,1981,"Washington, District of Columbia, USA",9780765378040.0,"""The long years of near-utopia have come to an...",...,False,False,12,36,1,0,True,False,USA,Central/North America
100262,2131878,Seven Surrenders,Ada Palmer,2017,2017-02-00,Tor,1981,"Washington, District of Columbia, USA",9780765378026.0,"""It is a world in which near-instantaneous tra...",...,False,True,02,36,1,0,True,True,USA,Central/North America
128775,2923757,Perhaps the Stars,Ada Palmer,2021,2021-10-19,Ad Astra / Head of Zeus,1981,"Washington, District of Columbia, USA",9781786699602.0,The leaders of Hive nations—nations without fi...,...,False,False,10,40,1,1,True,True,USA,Central/North America

In [19]:
books.sample(15)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,...,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before,author_birthplace_country,author_birthplace_continent
93985,2163763,The Knighthood,Evan Currie,2017,2017-02-08,Evan Currie,<NA>,NaN,NaN,NaN,...,False,False,02,Unknown,0,0,False,False,Unknown,Unknown
95116,2157009,Samaritan,Michael Dempsey (I),2017,2017-01-16,Michael Dempsey (I),<NA>,NaN,9781542386883.0,NaN,...,False,False,01,Unknown,0,0,False,False,Unknown,Unknown
11699,8585,Alanna: The First Adventure,Tamora Pierce,1983,1983-09-00,Beaver Books,1954,"South Connellsville, Pennsylvania, USA",0099435608,NaN,...,False,False,09,29,0,0,False,False,USA,Central/North America
105281,2393774,Yard Full of Bones,"Armand Rosamilia, Jay Wilburn",2018,2018-04-13,Unnerving,<NA>,"New Jersey, USA",9781775254423.0,NaN,...,False,False,04,Unknown,0,0,False,False,USA,Central/North America
130807,3034546,Shaken,Russell Zimmerman,2021,2021-07-21,Catalyst Game Labs,<NA>,NaN,NaN,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
149046,3474208,A Throne of Shadows,Tessonja Odette,2025,2025-04-01,Crystal Moon Press,<NA>,NaN,9781955960311.0,NaN,...,False,False,04,Unknown,0,0,False,False,Unknown,Unknown
114359,2627044,The Darkest Touch,Jaci Burton,2019,2019-05-30,Jaci Burton,<NA>,NaN,9781946535344.0,NaN,...,False,False,05,Unknown,0,0,False,False,Unknown,Unknown
6924,947218,Vicious Spiral,James Ryder,1976,1976-00-00,Robert Hale,1915,"East Harling, Norfolk, England, UK",0709157959,NaN,...,False,False,Unknown,61,0,0,False,False,UK,Europe
54757,1170695,Cryoburn,Lois McMaster Bujold,2010,2010-10-00,Baen Books,1949,"Columbus, Ohio, USA",9781439133941,Kibou-daini is a planet obsessed with cheating...,...,True,True,10,61,9,18,True,True,USA,Central/North America
15806,16213,Dawn for a Distant Earth,"L. E. Modesitt, Jr.",1987,1987-01-00,Tor,1943,"Denver, Colorado, USA",0812516133,"L. E. Modesitt, Jr's first major work was The ...",...,False,False,01,44,0,0,False,False,USA,Central/North America
75017,2147571,King of Prey,Mandy M. Roth,2014,2014-05-20,The Raven Books,<NA>,NaN,9781499635645.0,NaN,...,False,False,05,Unknown,0,0,False,False,Unknown,Unknown
54199,1220185,Lunatics and Luck,Marcus Sedgwick,2010,2010-03-04,Orion Children's Books,1968,"Preston, Kent, England, UK",9781842556955,Full moons and money troubles are nothing out ...,...,False,False,03,42,0,0,False,False,UK,Europe
26449,939695,Sweeter Savage Love,Sandra Hill,1997,1997-00-00,Love Spell,<NA>,"Lock Haven, Pennsylvania, USA",0505522128,THE STROKE OF SURPRISINGLY GENTLE HANDS... THE...,...,False,False,Unknown,Unknown,0,0,False,False,USA,Central/North America
75835,2235717,Fight and the Fury,Craig Halloran,2014,2014-08-10,Two-Ten Book Press,<NA>,"Charleston, West Virginia, USA",9781941208557.0,NaN,...,False,False,08,Unknown,0,0,False,False,USA,Central/North America
90886,2148843,Watershed,Jane Abbott,2016,2016-05-30,Random House Australia,<NA>,NaN,9780143780731.0,NaN,...,False,False,05,Unknown,0,0,False,False,Unknown,Unknown

In [20]:
## Add column with boolean if author been nominated for Hugo/Locus prior to that date
books['Hugo_Nominee_Before'] = 'False'
books['Hugo_Nominee_Before'] = books['Hugo_Nominee_Before'].case_when([(books['Hugo_Awards_Previously'] > 0,True)])
books['Locus_Nominee_Before'] = 'False'
books['Locus_Nominee_Before'] = books['Locus_Nominee_Before'].case_when([(books['Locus_Awards_Previously'] > 0,True)])

In [21]:
books.sample(100)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,...,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before,author_birthplace_country,author_birthplace_continent
99642,2387234,The Wolf's Dream Mate,"Marianne Morea, Milly Taiden",2017,2017-09-12,Coventry Press,<NA>,"New York City, New York, USA",NaN,NaN,...,False,False,09,Unknown,0,0,False,False,USA,Central/North America
57689,1614745,Springman Brothers' Reality Repair,Joshua Wright,2011,2011-00-00,Scholastic Press / Scholastic Australia,<NA>,"Geelong, Victoria, Australia",9781741697858,NaN,...,False,False,Unknown,Unknown,0,0,False,False,Australia,Oceania
5354,18375,The Demon Lover,Dion Fortune,1972,1972-00-00,Aquarian Press,1890,"Bryn-y-Bia, Llandudno, Caernarvonshire, Wales, UK",0850308216,NaN,...,False,False,Unknown,82,0,0,False,False,UK,Europe
132626,3320246,Crown of Lies,Annika West,2022,2022-08-25,Mad Hag Publishing,<NA>,NaN,9798848044034.0,NaN,...,False,False,08,Unknown,0,0,False,False,Unknown,Unknown
97941,2331544,Duchess of Terra,Glynn Stewart,2017,2017-02-10,Faolan's Pen Publishing,<NA>,NaN,9781988035147.0,To preserve humanity's survival and freedom in...,...,False,False,02,Unknown,0,0,False,False,Unknown,Unknown
96150,2715119,Valley of Vengeance,Franklin Horton,2017,2017-06-15,Franklin Horton,<NA>,NaN,9781547192113.0,NaN,...,False,False,06,Unknown,0,0,False,False,Unknown,Unknown
111465,2561810,Betrayal in Time,Julie McElwain,2019,2019-07-02,Pegasus Crime,<NA>,NaN,9781643130743.0,Kendra Donovan’s adventures in nineteenth-cent...,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
71979,1529042,Prodigy,Marie Lu,2013,2013-01-29,G. P. Putnam's Sons,1984,"Wuxi, Jiangsu Province, China",9780399256769.0,From copyright page: June and Day make their w...,...,False,False,01,29,0,0,False,False,China,Asia
35554,853216,Wonder Woman: Mythos,Carol Lay,2003,2003-01-00,Pocket Books,1952,"Whittier, California, USA",0743417119,While investigating the bizarre disappearance ...,...,False,False,01,51,0,0,False,False,USA,Central/North America
26019,178278,Body Switchers from Outer Space,"Nina Kiriki Hoffman, R. L. Stine",1996,1996-11-00,Pocket Books,1943,"Columbus, Ohio, USA",0671001868,A humorous tale of an alien who wants to switc...,...,False,False,11,53,0,0,False,False,USA,Central/North America
148540,3569522,A Testimony of Blood,Rogba Payne,2025,2025-07-17,Gollancz,<NA>,NaN,9781399612692.0,'A bird in a cage may be safe but it will know...,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
20177,183420,Battleground,W. E. B. Griffin,1991,1991-09-01,Jove Books,1929,"Newark, New Jersey, USA",0515106402,"W.E.B. Griffin is a bestselling phenomenom, an...",...,False,False,09,62,0,0,False,False,USA,Central/North America
101862,2674370,Becoming Briar,"Nicole Kelley, Erin West",2018,2018-07-26,Nicole Kelley & Erin West,<NA>,NaN,9781717897817.0,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
15540,3101087,Seaside Mystery,Ann Hodgman,1987,1987-05-00,Bantam Books,1956,NaN,0553276964,NaN,...,False,False,05,31,0,0,False,False,Unknown,Unknown
139755,3186148,Grave Expectations,Alice Bell,2023,2023-05-04,Corvus,<NA>,NaN,9781838958398.0,"A fast-paced and hilarious debut crime novel, ...",...,False,False,05,Unknown,0,0,False,False,Unknown,Unknown
114414,2743091,Smoke & Mirrors,C. L. Schneider,2019,2019-06-02,C. L. Schneider,<NA>,NaN,9781095152317.0,NaN,...,False,False,06,Unknown,0,0,False,False,Unknown,Unknown
124045,2817049,Skulduggery 2,Logan Jacobs,2020,2020-03-24,Logan Jacobs,<NA>,NaN,NaN,NaN,...,False,False,03,Unknown,0,0,False,False,Unknown,Unknown
109802,2833909,Under the Lies,A. K. Koonce,2019,2019-08-30,A. K. Koonce,<NA>,NaN,9781692035228.0,They pushed too far. The demented Hatter and a...,...,False,False,08,Unknown,0,0,False,False,Unknown,Unknown
81910,1889114,The Broken World,J. D. Oswald,2015,2015-09-24,Penguin Books,<NA>,NaN,9781405917780.0,"The book, sir. The Llyfr Draconius. You'll fin...",...,False,False,09,Unknown,0,0,False,False,Unknown,Unknown
122424,2721948,Relics of Eternity,Glynn Stewart,2020,2020-04-01,Faolan's Pen Publishing,<NA>,NaN,9781989674062.0,Seeking to escape the shadow of Annette Bond's...,...,False,False,04,Unknown,0,0,False,False,Unknown,Unknown
1738,21186,The Long Winter,John Christopher,1962,1962-03-00,Fawcett Crest,1922,"Huyton, Lancashire, England, UK",NaN,NaN,...,False,False,03,40,0,0,False,False,UK,Europe
74378,1724416,The Shadows,Megan Chance,2014,2014-06-03,Skyscape,1959,"Columbus, Ohio, USA",9781477847183.0,NaN,...,False,False,06,55,0,0,False,False,USA,Central/North America
63852,1373669,Queen Rat,Kim Lakin-Smith,2012,2012-01-31,Murkee,1972,"Burton-upon-Trent, Staffordshire, England, UK",9781906584306,NaN,...,False,False,01,40,0,0,False,False,UK,Europe
129687,2834924,What You Never Knew,Jessica Hamilton,2021,2021-04-06,Dreamscape Media,<NA>,NaN,9781662090776.0,NaN,...,False,False,04,Unknown,0,0,False,False,Unknown,Unknown
120003,2808424,The Rebirth,Doug Dandridge,2020,2020-01-26,Catbrother Publishing,1957,"Venice, Florida, USA",NaN,NaN,...,False,False,01,63,0,0,False,False,USA,Central/North America
9832,1074428,The Embryo,Andrew Laurance,1980,1980-10-16,Star / W. H. Allen,1930,"London, England, UK",0352306513,NaN,...,False,False,10,50,0,0,False,False,UK,Europe
141565,3233209,Raven's Flag,Glynn Stewart,2023,2023-10-03,Faolan's Pen Publishing,<NA>,NaN,9781989674413.0,The United Planets Alliance fought the Kenmiri...,...,False,False,10,Unknown,0,0,False,False,Unknown,Unknown
118040,3283013,Fireforged,Ahava Trivedi,2020,2020-12-07,Ahava Trivedi,<NA>,NaN,9798496622455.0,NaN,...,False,False,12,Unknown,0,0,False,False,Unknown,Unknown
80241,2451678,Smoke and Rain,V. S. Holmes,2015,2015-09-19,Amphibian Press,<NA>,NaN,9780996133005.0,"I expected a hero to save us all. Turns out, I...",...,False,False,09,Unknown,0,0,False,False,Unknown,Unknown
110631,2581601,Fair Trade,Gre7g Luterman,2019,2019-01-23,Thurston Howl Publications,1967,NaN,9781945247460.0,NaN,...,False,False,01,52,0,0,False,False,Unknown,Unknown
79112,1779322,The Book of Storms,Ruth Hatfield,2014,2014-11-06,Hot Key Books,<NA>,NaN,9781471402982.0,NaN,...,False,False,11,Unknown,0,0,False,False,Unknown,Unknown
93031,2034663,The Forgetting,Sharon Cameron,2016,2016-09-13,Scholastic Press,1970,"Nashville, Tennessee, USA",9780545945219.0,From beloved author of Rook comes a brilliant ...,...,False,False,09,46,0,0,False,False,USA,Central/North America
82581,1920671,"Ice Magic, Fire Magic",Shauna Roberts,2015,2015-08-28,Hadley Rille Books,1956,"Dayton, Ohio, USA",9780989263184.0,NaN,...,False,False,08,59,0,0,False,False,USA,Central/North America
78389,1992435,The Sweet Smell of Avalon,George W. Harper,2014,2014-08-25,CreateSpace,1927,"Chicago, Illinois, USA",9781499126204.0,NaN,...,False,False,08,87,0,0,False,False,USA,Central/North America
30854,9421,Mina,Elaine Bergstrom,2000,2000-09-00,Ace Books,1946,"Cleveland, Ohio, USA",0441006620,**From the rear flap of the book club edition:...,...,False,False,09,54,0,0,False,False,USA,Central/North America
21589,19116,A Case of Need,Michael Crichton,1993,1993-07-00,Dutton,1942,"Chicago, Illinois, USA",0525938028,The author of cutting-edge bestsellers like Ju...,...,False,False,07,51,0,1,False,True,USA,Central/North America
11648,7736,The Walls of Air,Barbara Hambly,1983,1983-03-00,Del Rey / Ballantine,1951,"San Diego, California, USA",0345296702,A “tense and nerve-wracking” adventure in the ...,...,False,False,03,32,0,0,False,False,USA,Central/North America
100827,2550663,A Prisoner of Mars,Rob Dorsey,2017,2017-02-06,Copper Creek Press,1947,"Athens, Texas, USA",9780986313615.0,NaN,...,False,False,02,70,0,0,False,False,USA,Central/North America
67369,1433721,Once Burned,Jeaniene Frost,2012,2012-06-26,Avon / HarperCollins,1974,NaN,9780062096272.0,"Doomed to a life of solitude, Leila, who has t...",...,False,False,06,38,0,0,False,False,Unknown,Unknown
62786,1469746,Blink Once,Cylin Busby,2012,2012-09-04,Bloomsbury USA,1970,"Massachusetts, USA",9781599908182,"West, a high school senior with everything goi...",...,False,False,09,42,0,0,False,False,USA,Central/North America
81132,2281471,Protection,Elle Thorne,2015,2015-01-24,Barbed Borders Press,<NA>,NaN,NaN,NaN,...,False,False,01,Unknown,0,0,False,False,Unknown,Unknown
49327,1355521,Twenties Girl,Sophie Kinsella,2009,2009-07-01,The Dial Press,1969,"Wandsworth, London, England, UK",9780385342032,Lara Lington has always had an overactive imag...,...,False,False,07,40,0,0,False,False,UK,Europe
52050,1104836,Beast Warrior: Viking Werewolf,Eva Gordon,2009,2009-07-31,Vanilla Heart Publishing,<NA>,NaN,9781935407317,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
7097,5081,The World Below,S. Fowler Wright,1976,1976-00-00,"World Editions, Inc.",1874,"Kings Norton, Birmingham, Warwickshire, Englan...",0883554666,NaN,...,False,False,Unknown,102,0,0,False,False,UK,Europe
67314,1415428,Bound to Me,Jocelynn Drake,2012,2012-04-10,Harper Voyager,1977,"Covington, Kentucky, USA",9780062118219.0,"Mira, the heroine of Jocelynn Drake's New York...",...,False,False,04,35,0,0,False,False,USA,Central/North America
25941,3165,Ancient Shores,Jack McDevitt,1996,1996-04-00,HarperPrism,1935,"Philadelphia, Pennsylvania, USA",0061052078,It turned up in a North Dakota wheat field: a ...,...,False,False,04,61,0,3,False,True,USA,Central/North America
40719,658089,Fairy Dust and the Quest for the Egg,Gail Carson Levine,2005,2005-00-00,Funtastic Publishing,1947,"New York City, New York, USA",1741504821,NaN,...,False,False,Unknown,58,0,0,False,False,USA,Central/North America
87787,3361952,All Lesser Means,J. A. Pipes,2016,2016-11-01,ALM Publishing LLC,<NA>,NaN,NaN,What if information from the future could make...,...,False,False,11,Unknown,0,0,False,False,Unknown,Unknown
118524,3038586,Mortal Imperative,R. L. King,2020,2020-12-14,Magespace Press,<NA>,NaN,9781953063045.0,Alastair Stone is surprised when a long-forgot...,...,False,False,12,Unknown,0,0,False,False,Unknown,Unknown
127743,2880614,The Mad Elf,Ned Caratacus,2021,2021-08-24,Aethon Books,<NA>,NaN,9798468944028.0,NaN,...,False,False,08,Unknown,0,0,False,False,Unknown,Unknown
137395,3337671,The Rosewood Penny,J. S. Fields,2023,2023-12-12,Space Wizard Science Fantasy,<NA>,NaN,9781960247162.0,"\n● ""In a reclusive forest, lives bandit lea...",...,False,False,12,Unknown,0,0,False,False,Unknown,Unknown
78475,1765733,Zombies of the Caribbean,John Kloepfer,2014,2014-10-07,HarperCollins,<NA>,NaN,9780062290243.0,NaN,...,False,False,10,Unknown,0,0,False,False,Unknown,Unknown
79717,2668990,Diaries of the Damned,Alex Laybourne,2015,2015-08-03,Severed Press,<NA>,"Lowestoft, Suffolk, England, UK",9781925342376.0,NaN,...,False,False,08,Unknown,0,0,False,False,UK,Europe
112040,2546982,Hilda and the Great Parade,Stephen Davies,2019,2019-01-22,Flying Eye Books,1976,NaN,9781911171454.0,NaN,...,False,False,01,43,0,0,False,False,Unknown,Unknown
57633,1297785,Immortal Beloved,Katie M. John,2011,2011-08-25,Little Bird Publishing House,1980,UK,9780956739544,NaN,...,False,False,08,31,0,0,False,False,UK,Europe
4510,2009857,The Mating,Eric Jay,1970,1970-08-00,Midwood Books,<NA>,NaN,NaN,A souped-up computer named ONE achieves sentie...,...,False,False,08,Unknown,0,0,False,False,Unknown,Unknown
65755,1593138,Pulling Up Stakes: A Tale of Relenting Horror,Peter David,2012,2012-09-20,Crazy 8 Press,1956,"Fort Meade, Maryland, USA",9780983687733.0,NaN,...,False,False,09,56,0,0,False,False,USA,Central/North America
99205,2320310,The Unnamed Way,Ian W. Sainsbury,2017,2017-09-02,Ian W. Sainsbury,<NA>,NaN,9781975675158.0,NaN,...,False,False,09,Unknown,0,0,False,False,Unknown,Unknown
51538,1067877,Whitby Vampyrrhic,Simon Clark,2009,2009-11-04,Severn House,1958,"Doncaster, Yorkshire, England, UK",9780727868312,"Set in 1942, long before the first two novels ...",...,False,False,11,51,0,0,False,False,UK,Europe
58037,1286375,Texas Gothic,Rosemary Clement-Moore,2011,2011-07-07,RHCP Digital,<NA>,"Texas, USA",9780552564939,Seventeen-year-old Amy Goodnight has long been...,...,False,False,07,Unknown,0,0,False,False,USA,Central/North America
110072,2517284,Hole in the World,Brian Keene,2019,2019-02-26,Apex Publications,1967,"Pennsylvania, USA",9781937009724.0,NaN,...,False,False,02,52,0,0,False,False,USA,Central/North America
43071,196575,Immersion,Steven Kornegay,2006,2006-10-15,Righter Publishing Company,<NA>,NaN,0976603217,NaN,...,False,False,10,Unknown,0,0,False,False,Unknown,Unknown
121671,2733682,The Kinder Poison,Natalie Mae,2020,2020-06-16,Razorbill,<NA>,NaN,9781984835215.0,NaN,...,False,False,06,Unknown,0,0,False,False,Unknown,Unknown
21321,13935,Don't Take Away the Light,J. N. Williamson,1993,1993-04-00,Zebra Books / Kensington Publishing Corp.,1932,"Indianapolis, Indiana, USA",0821741284,NaN,...,False,False,04,61,0,0,False,False,India,Central/North America
68327,2241284,Unleash,Felicity Heaton,2013,2013-05-00,Felicity Heaton,<NA>,NaN,9781484164211.0,"A powerful vampire lost deep in his bloodlust,...",...,False,False,05,Unknown,0,0,False,False,Unknown,Unknown
125629,3286071,Eagle's Flame,K. L. King,2021,2021-06-23,K. L. King,<NA>,NaN,9798512045701.0,NaN,...,False,False,06,Unknown,0,0,False,False,Unknown,Unknown
85303,2805318,Infinite,Erica Crouch,2015,2015-05-29,Patchwork Press,<NA>,NaN,9781927940372.0,NaN,...,False,False,05,Unknown,0,0,False,False,Unknown,Unknown
5519,3914,Marion's Wall,Jack Finney,1973,1973-04-00,Warner Paperback Library,1911,"Milwaukee, Wisconsin, USA",0446763640,NaN,...,False,False,04,62,0,0,False,False,USA,Central/North America
61205,1324012,Revan,Drew Karpyshyn,2011,2011-11-00,Titan Books,1971,"Edmonton, Alberta, Canada",9780857689009,"Hero, traitor, conqueror, villain, savior -- t...",...,False,False,11,40,0,0,False,False,Canada,Central/North America
7506,1517,Mirkheim,Poul Anderson,1977,1977-01-00,Sphere,1926,"Bristol, Pennsylvania, USA",0722111460,NaN,...,False,True,01,51,6,7,True,True,USA,Central/North America
129651,2832210,Mariner Valley,James Crawford,2021,2021-01-01,James Crawford,<NA>,NaN,9780578832678.0,NaN,...,False,False,01,Unknown,0,0,False,False,Unknown,Unknown
28272,907772,Stardust,Neil Gaiman,1998,1998-00-00,Harper Perennial,1960,"Porchester, Hampshire, England, UK",9780061142024,Tristran thorn promised to bring back a fallen...,...,False,True,Unknown,38,0,0,False,False,UK,Europe
82995,1916088,Pathfinder,Gun Brooke,2015,2015-11-10,Bold Strokes Books,1960,"Helsingborg, Sweden",9781626394445.0,NaN,...,False,False,11,55,0,0,False,False,Sweden,Europe
59880,1353867,Contingencies,Thomas White,2011,2011-10-18,Ocean Beach Kft. LLC,<NA>,NaN,9780615545356,NaN,...,False,False,10,Unknown,0,0,False,False,Unknown,Unknown
51349,1064826,Veracity,Laura Bynum,2009,2009-12-26,Pocket Books,1968,"Springfield, Illinois, USA",9781439123348,NaN,...,False,False,12,41,0,0,False,False,USA,Central/North America
4183,1191,Slaughterhouse-Five,Kurt Vonnegut,1970,1970-00-00,Dell,1922,"Indianapolis, Indiana, USA",0440180295,"Slaughterhouse-Five, or The Children's Crusade...",...,True,False,Unknown,48,0,0,False,False,India,Central/North America
56650,1108799,Dungeon Crawlers: Episode 1,Stefan U. G. LeBlanc,2010,2010-04-08,TIAC Communications,1989,"Vancouver, British Columbia, Canada",9781896780030,NaN,...,False,False,04,21,0,0,False,False,Canada,Central/North America
15371,2912705,Smithereens,B. W. Battin,1987,1987-09-00,Fawcett Gold Medal / Ballantine,1941,"Ridgewood, New Jersey, USA",0449132226,NaN,...,False,False,09,46,0,0,False,False,USA,Central/North America
42473,184796,Chasing the Dead,Joe Schreiber,2006,2006-10-00,Ballantine Books,1969,"Michigan, USA",0345487478,"""You have a very lovely little girl,"" breathed...",...,False,False,10,37,0,0,False,False,USA,Central/North America
80207,2310109,Power,Harmony Raines,2015,2015-07-22,Silver Moon Erotica,<NA>,NaN,NaN,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
40999,1020342,The Black Sphinx,Matt Hart,2006,2006-03-00,Corgi,1969,NaN,0552554219,NaN,...,False,False,03,37,0,0,False,False,Unknown,Unknown
53266,1145492,The Khan Saga,Talessian El-Wikosian,2010,2010-07-09,Reality Six,<NA>,NaN,9780981375397,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
18151,15403,Viper,Alan Riefe,1990,1990-12-00,Diamond Books,1925,"Waterbury, Connecticut, USA",1557734305,NaN,...,False,False,12,65,0,0,False,False,USA,Central/North America
35124,1964613,Jumping the Jack,"Clayton Emery, Earl Wajenberg",2003,2003-02-00,Wildside Press,1953,NaN,1587157225,NaN,...,False,False,02,50,0,0,False,False,Unknown,Unknown
80895,2345868,The Last Road Home,Hope Erica Schultz,2015,2015-12-11,CHBB Publishing,<NA>,NaN,9781519795731.0,NaN,...,False,False,12,Unknown,0,0,False,False,Unknown,Unknown
99032,2312164,Mars,Becca Fanning,2017,2017-01-17,Becca Fanning,<NA>,NaN,NaN,NaN,...,False,False,01,Unknown,0,0,False,False,Unknown,Unknown
123969,2872013,Witcher Upper,Amy Boyles,2020,2020-06-12,Ladybugbooks,<NA>,NaN,9798651918539.0,NaN,...,False,False,06,Unknown,0,0,False,False,Unknown,Unknown
127698,3017949,Stealing Time,Rebecca Bowyer,2021,2021-03-03,Story Addict Publishing,<NA>,NaN,9780648532330.0,NaN,...,False,False,03,Unknown,0,0,False,False,Unknown,Unknown
2521,152529,Visa for Avalon,Bryher,1965,1965-00-00,Paris Press,1894,"Margate, Kent, England, UK",193046407X,NaN,...,False,False,Unknown,71,0,0,False,False,UK,Europe
7305,1985908,The Man-Made Woman,Robert Franklin Murphy,1976,1976-00-00,Zebra Books / Kensington Publishing Corp.,<NA>,NaN,0890831793,NaN,...,False,False,Unknown,Unknown,0,0,False,False,Unknown,Unknown
17556,15637,In Hot Blood,Petru Popescu,1989,1989-01-00,Fawcett Gold Medal / Ballantine,1944,"Bucharest, Romania",0449145549,NaN,...,False,False,01,45,0,0,False,False,Romania,Europe
38998,181294,Fly by Night,Frances Hardinge,2005,2005-10-00,HarperCollins,1973,"Brighton, East Sussex, England, UK",0060876298,Twelve-year-old Mosca Mye hasn't got much. Her...,...,False,False,10,32,0,0,False,False,UK,Europe
14282,14377,Evil Dreams,John Tigges,1986,1986-00-00,Leisure Books,1932,"Dubuque, Indiana, USA",0843927534,NaN,...,False,False,Unknown,54,0,0,False,False,India,Central/North America
148101,3577746,Nine Rivers Sect,Greg Tolley,2025,2025-12-17,Mountaindale Press,<NA>,NaN,9781637663363.0,NaN,...,False,False,12,Unknown,0,0,False,False,Unknown,Unknown
112511,2835762,Old Bones,"Douglas Preston, Lincoln Child",2019,2019-08-00,Grand Central Publishing,1957,"Westport, Connecticut, USA",9781538747223.0,"Het waargebeurde, noodlottige verhaal van de D...",...,False,False,08,62,0,0,False,False,USA,Central/North America
53400,1131714,The Sacrifice,Samantha Sommersby,2010,2010-07-06,Samhain Publishing,<NA>,NaN,9781605047713,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
117775,3025957,Southern Blood,Stuart Jaffe,2020,2020-08-06,Stuart Jaffe,1971,"New Jersey, USA",9798673317242.0,NaN,...,False,False,08,49,0,0,False,False,USA,Central/North America
54953,1075092,Gone,Lisa McMann,2010,2010-02-09,Simon Pulse,1968,"Holland, Michigan, USA",9781416979180,NaN,...,False,False,02,42,0,0,False,False,USA,Central/North America
43195,221101,The Freakshow,Bryan Smith,2007,2007-03-00,Leisure Books / Dorchester Publishing,1965,NaN,0843958278,Poems.\n\n,...,False,False,03,42,0,0,False,False,Unknown,Unknown
124577,2810845,A Duet of Sword and Song,Lisa Cassidy,2020,2020-09-06,Tate House,<NA>,"Melbourne, Australia",9780648539285.0,The time of the Shadowhawk was gone. Now he ne...,...,False,False,09,Unknown,0,0,False,False,Australia,Oceania

In [22]:
## Add Author Birthplace by country
replace_dict = {'Austria':['Austria-Hungary','Austro-Hungarian Empire','Austria'],
               'Russia':['Russian Empire','Russia','USSR','Soviet'],
               'Germany':['German Empire','Reich','Confederation','Germany','Prussia'],
               'Nigeria':['Nigeria'],
               'India':['INdia','India'],
               'Peru':['Perú','Peru'],
               'Ceylon':['Ceylon'],
               'Papua New Guinea':['Netherlands New Guinea'],
               'Hong Kong':['Territory','Kong','Hong Kong','Komg'],
               'Dominican Republic':['Dominican Republic'],
               'Bailiwack of Jersey':['Balliwack of Jersey','Bailiwick of Jersey'],
               'Trinidad and Tobago':['Tobago','Trinidad'],
               'UK': ['Yorkshire','Wales','England','United Kingdom','UK','Scotland','Northern Ireland','Guernsey','Britain'],
               'Australia':['Sydney','New South Wales','Australia','Queensland','Victoria','Gold Coast'],
               'USA':['Philadelphia','MO','PA','WA','PR','Baltimore','USA','US Virgin Islands','Puerto Rico'],
               'Panama':['Canal Zone','Panama'],
               'Sri Lanka': ['Lanka'],
               'New Zealand':['Zealand','NZ'],
               'East Indies' :['East Indies'],
                'West Indies' :['West Indies','Antilles','Dominica'],
                'El Salvador' :['El Salvador'],
                'South Africa' :['Cape Colony','Pretoria','Port Elizabeth','South Africa','Orange Free'],
                'United Arab Emirates' :['United Arab Emirates'],
                'Sierra Leone' :['Sierra Leone'],
                'Canada': ['British North America','Canada','Alberta'],
                'Guyana':['Guyana','British Guiana'],
                'Cayman Islands': ['Cayman'],
                'Marshall Islands':['Marshall'],
                'Thailand': ['Thailand','Siam'],
                'Malaysia':['Malaya','Malaysia'],
                'Philipines':['Philipines','Philippine Islands'],
                'Ireland' : ['Ireland','Irish'],
                'Turkey':['Turkey','Ottoman Empire'],
                'Rhodesia':['Rhodesia'],
                'Bermuda':['Bermuda'],
                'Kenya':['Kenya'],
                'Jamaica':['Jamaica'],
                'Sweden':['Sweden','Swedish'],
                'Singapore':['Singapore'],
                'Nyasaland':['Nyasaland'],
                'Palestine':['Palestine'],
                'Fiji':['Fiji'],
                'Holy Roman Empire':['Holy Roman Empire'],
                'Myanmar':['Burma','Myanmar'],
                'Malta':['Malta'],
                'Czech Republic':['Czech'],
                'Rwanda':['Rwanda','Portugese West Africa','Kamundongo']
}

def replace_author_birthplace_country(x):
    if pd.isna(x):
        return 'Unknown'
    for country, birthplace in replace_dict.items():
        if any(word in x for word in birthplace):
            return country
    if x not in replace_dict.items():
        return x.strip().split()[-1]
    return x

In [23]:
books = books.assign(author_birthplace_country=books['author_birthplace'].apply(replace_author_birthplace_country))
books.sample(15)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,...,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before,author_birthplace_country,author_birthplace_continent
108682,2357769,Ravencry,Ed McDonald,2018,2018-06-28,Gollancz,<NA>,NaN,9781473222052.0,"'Dark, twisty and excellent . . . Grimdark wit...",...,False,False,06,Unknown,0,0,False,False,Unknown,Unknown
34818,1150836,Blood of the Tribe,David S. Brody,2003,2003-06-01,Martin and Lawrence Press,<NA>,NaN,0972168710,NaN,...,False,False,06,Unknown,0,0,False,False,Unknown,Unknown
78682,1734437,The Great Day,Robert Reed,2014,2014-02-04,Prime Books,1956,"Omaha, Nebraska, USA",9781607014263.0,NaN,...,False,False,02,58,0,5,False,True,USA,Central/North America
6397,27065,A Stranger Came Ashore,Mollie Hunter,1975,1975-08-07,HarperTrophy,1922,"Longniddry, East Lothian, Scotland, UK",0064400824,"* Set in the Shetland Islands \n * ""Twelve-...",...,False,False,08,53,0,0,False,False,UK,Europe
598,709361,One Against the Moon,Donald A. Wollheim,1956,1956-00-00,World Publishing Co.,1914,"New York City, New York, USA",9781612871523,NaN,...,False,False,Unknown,42,0,0,False,False,USA,Central/North America
35550,985202,Jihad,James Swallow,2003,2003-12-31,Big Finish Productions,1970,"London, England, UK",1844350525,NaN,...,False,False,12,33,0,0,False,False,UK,Europe
106270,2581337,Forever Endangered,Carolina Montague,2018,2018-03-14,The Wild Rose Press,<NA>,NaN,9781509219735.0,NaN,...,False,False,03,Unknown,0,0,False,False,Unknown,Unknown
129454,2838044,Noob Game Plus,Ryan Rimmel,2021,2021-02-22,Ryan Rimmel,<NA>,NaN,9781039400016.0,What happened? The last thing Jim remembered w...,...,False,False,02,Unknown,0,0,False,False,Unknown,Unknown
59544,1249303,Woke Up in a Strange Place,Eric Arvin,2011,2011-02-25,Dreamspinner Press,<NA>,NaN,9781615817955,NaN,...,False,False,02,Unknown,0,0,False,False,Unknown,Unknown
97928,2189937,Shattered Minds,Laura Lam,2017,2017-06-15,Macmillan UK,<NA>,USA,9781447286905.0,Laura Lam's Shattered Minds stars a female 'De...,...,False,False,06,Unknown,0,0,False,False,USA,Central/North America
75911,1679842,Opal Moonbaby Forever,Maudie Smith,2014,2014-02-06,Orion Children's Books,<NA>,NaN,9781444004809.0,NaN,...,False,False,02,Unknown,0,0,False,False,Unknown,Unknown
144649,3317750,Hunting Grounds,G. Allen Wilbanks,2024,2024-05-09,Deep Dark Thoughts Publications,<NA>,"San Jose, California, USA",9781952630101.0,"The testing grounds are closed, but that does ...",...,False,False,05,Unknown,0,0,False,False,USA,Central/North America
134735,3199840,Colossus,Greg Leunig,2022,2022-09-00,Spaceboy Books,<NA>,NaN,9781951393175.0,NaN,...,False,False,09,Unknown,0,0,False,False,Unknown,Unknown
111912,2551912,Nightfall,Andrew J. Harvey,2019,2019-02-01,Zmok Books,<NA>,NaN,9781945430947.0,NaN,...,False,False,02,Unknown,0,0,False,False,Unknown,Unknown
37200,153698,The Trapping,Anthony Vela,2004,2004-01-00,Xlibris Corporation,<NA>,"West Islip, New York, USA",1413423493,NaN,...,False,False,01,Unknown,0,0,False,False,USA,Central/North America

In [24]:
## Author Birthplace by continent
continent_dict = {
'Africa' : ['Africa','Zambia','Libya','Sudan','Ethiopia','Madagascar','Morocco','Sudan','Namibia','Niger','Botswana','Liberia','Tunisia','Mauritius',
          'Nyasaland','Sierra Leone','Guinea','Tanzania','Zimbabwe','Uganda','Ghana','Egypt','Kenya','Rwanda','Nigeria','Rhodesia','South Africa',
          ],
'Europe' : ['Cyprus','Marino','Macedonia','Latvia','Holy Roman Empire','Luxembourg','Gibraltar','Bulgaria','Ukraine','Serbia','Bailiwack of Jersey',
          'Denmark','Norway','Iceland','Czech Republic','Greece','Hungary','Finland','Spain','Romania','Malta','Belgium','Poland','Portugal',
          'Switzerland','Yugoslavia','Austria','Sweden','Italy','Netherlands','France','Russia','Germany','Ireland','UK'],
'South America' : ['Suriname','Uruguay','Bolivia','Colombia','Guyana','Chile','Ecuador','Peru','Argentina','Brazil','Venezuela'],
'Central/North America' : ['USA','Honduras','Bahamas','Guatemala','Barbados','Cayman Islands','Croatia','Grenada','Panama','Jamaica','Bermuda',
                         'Haiti','Trinidad and Tobago','Cuba','West Indies','Mexico','Dominican Republic','Canada'],
'Asia' : ['Iraq','East Indies','Myanmar','Philippines','Brunei','Macau','Kuwait','Nepal','United Arab Emirates','Bahrain','Vietnam','Laos','Arabia',
        'Pakistan','Palestine','Sri Lanka','Bangladesh','Persia','Turkey','Lebanon','Ceylon','Korea','Thailand','Indonesia','Taiwan','Iran',
        'Singapore','Malaysia','Philippines','Hong Kong','China','Israel','Japan','India'],
'Oceania' : ['Australia','New Zealand','Samoa','Marshall Islands','Papua New Guinea','Fiji']
}

def replace_author_birthplace_continent(x):
    if pd.isna(x):
        return 'Unknown'
    for country, birthplace in continent_dict.items():
        if any(word in x for word in birthplace):
            return country
    if x not in replace_dict.items():
        return x.strip().split()[-1]
    return x

In [25]:
books = books.assign(author_birthplace_continent=books['author_birthplace'].apply(replace_author_birthplace_continent))
books.sample(15)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,...,hugo,locus,month_of_publication,Author_Age_at_Publication,Hugo_Awards_Previously,Locus_Awards_Previously,Hugo_Nominee_Before,Locus_Nominee_Before,author_birthplace_country,author_birthplace_continent
146842,3333616,A Cruel Twist of Fate,H. F. Askwith,2024,2024-01-18,Penguin Books,<NA>,NaN,9780241629642.0,And Then There Were None meets The Inheritance...,...,False,False,01,Unknown,0,0,False,False,Unknown,Unknown
98845,2290095,Martha Mayhem and the Witch from the Ditch,Joanne Owen,2017,2017-07-27,Piccadilly Press Ltd,<NA>,"Neyland, Pembrokeshire, Wales, UK",9781848125360.0,NaN,...,False,False,07,Unknown,0,0,False,False,UK,Europe
120314,2776407,The Potion Diaries,Amy McCulloch,2020,2020-10-29,Simon & Schuster Children's UK,1986,"Kingston Upon Thames, London, England, UK",9781471198717.0,Samantha Kemi's ability to mix potions is need...,...,False,False,10,34,0,0,False,False,UK,Europe
119624,2753533,Alien Savage's Stolen Bride,Juno Wells,2020,2020-07-11,Looking Glass Publications,<NA>,NaN,9781948353304.0,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
11204,2060468,Lightfall,Paul Monette,1982,1982-10-00,Avon,1945,"Lawrence, Massachusetts, USA",0380810751,NaN,...,False,False,10,37,0,0,False,False,USA,Central/North America
108167,2371717,Every Time You Go Away,Beth Harbison,2018,2018-07-24,St. Martin's Press,1966,USA,9781250043832.0,In New York Times bestselling author Beth Harb...,...,False,False,07,52,0,0,False,False,USA,Central/North America
68475,2261944,Blood Roses,Lindsay J. Pryor,2013,2013-04-19,Bookouture,<NA>,NaN,9781909490031.0,"""She was supposed to kill vampires, not save t...",...,False,False,04,Unknown,0,0,False,False,Unknown,Unknown
4870,846252,Chalet Diabolique,Virginia Coffman,1971,1971-00-00,Lancer Books,1914,"San Francisco, California, USA",NaN,NaN,...,False,False,Unknown,57,0,0,False,False,USA,Central/North America
131939,3244721,Disciples,"Matthew Peed, Andrew Peed",2022,2022-09-01,Sprocketed Ink,<NA>,NaN,NaN,NaN,...,False,False,09,Unknown,0,0,False,False,Unknown,Unknown
109962,2831223,Iron Dogs,Anthony James,2019,2019-07-09,Anthony James,<NA>,NaN,9781080074839.0,NaN,...,False,False,07,Unknown,0,0,False,False,Unknown,Unknown
144422,3295364,The Witch Queen of Halloween,Kresley Cole,2024,2024-03-26,Valkyrie Press,<NA>,"Mobile, Alabama, USA",9798989376216.0,NaN,...,False,False,03,Unknown,0,0,False,False,USA,Central/North America
117601,3227005,"Aurifodina; Or, Adventures in the Gold Region",George Washington Peck,2020,2020-03-27,C. W. Gross,1817,"Rehoboth, Massachusetts, USA",9798630582072.0,NaN,...,False,False,03,203,0,0,False,False,USA,Central/North America
52764,1485054,The Fat Man: A Tale of North Pole Noir,Ken Harmon,2010,2010-10-28,Dutton,<NA>,NaN,9780525951957,NaN,...,False,False,10,Unknown,0,0,False,False,Unknown,Unknown
32834,1164098,Secrets of New Babylon,"Tim LaHaye, Jerry B. Jenkins, Chris Fabry",2002,2002-07-00,Tyndale House Publishers,1926,"Detroit, Michigan, USA",0842343156,Follow the Young Trib Force as they struggle t...,...,False,False,07,76,0,0,False,False,USA,Central/North America
128730,2959105,Escape from Chernobog,Ajax Lygan,2021,2021-05-31,Ajax Lygan,<NA>,NaN,NaN,NaN,...,False,False,05,Unknown,0,0,False,False,Unknown,Unknown

In [26]:
books.reset_index()
books.to_csv("data_with_author_and_awards.csv", index = False)