The purpose of this notebook is to look at a preliminary dataset and compare it with our datasets for Hugo and Locus finalists. We find in this preliminary examination some issues with the dataset such as nonmatching award entries. Certain entry errors are documented below.

In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [120]:
locus = pd.read_csv('locus_nominees.csv')
locus.head()

                       title             author  year
0                  Ringworld        Larry Niven  1971
1             Tower of Glass  Robert Silverberg  1971
2  The Year of the Quiet Sun      Wilson Tucker  1971
3             And Chaos Died        Joanna Russ  1971
4      Downward to the Earth  Robert Silverberg  1971

In [121]:
hugo = pd.read_csv('hugo_nominees.csv')
hugo.head()

                    title                    author  year
0      The Demolished Man             Alfred Bester  1953
1  They'd Rather Be Right  Mark Clifton&Frank Riley  1955
2             Double Star        Robert A. Heinlein  1956
3         “Call Him Dead”        Eric Frank Russell  1956
4     The End of Eternity              Isaac Asimov  1956

In [122]:
books = pd.read_csv('isfdb-hardcover-combined.csv')
books.title = books.title.apply(lambda x : x.lower())
books.head()

,Unnamed: 0,title_id,author,release_year,release_date,author_age_at_release,author_birthplace,isbn,first_publisher,book_synopsis,tags,title
0,0,1,Geoff Ryman,1985,1985-05-00,34.0,Canada,0044407777,Unwin Paperbacks,<b>From the back cover of the Bantam paperback...,"['bsfa award for best novel finalist', 'fantas...",the warrior who carried life
1,1,4,Ben Bova,1973,1973-03-00,41.0,"Philadelphia, Pennsylvania, USA",0727817760,Severn House,NaN,"['science fiction', 'young-adult sf']",the winds of altair
2,2,6,Ben Bova,1993,1993-09-00,61.0,"Philadelphia, Pennsylvania, USA",0812511654,Tor,NaN,"['science fiction', 'Fantasy', 'Adventure', 'F...",empire builders
3,3,7,Ben Bova,1985,1985-10-00,53.0,"Philadelphia, Pennsylvania, USA",0812534891,Tor,NaN,['science fiction'],privateers
4,4,8,Ben Bova,1990,1990-04-00,58.0,"Philadelphia, Pennsylvania, USA",0312932154,Tor,A courageous astronaut braves the awesome powe...,"['nanotechnology', 'science fiction', 'Fantasy...",star brothers

In [123]:
hugo.title = hugo.title.apply(lambda x : x.lstrip('“').rstrip('”'))
hugo.title = hugo.title.apply(lambda x : x.lower())
hugo

                      title                    author  year
0        the demolished man             Alfred Bester  1953
1    they'd rather be right  Mark Clifton&Frank Riley  1955
2               double star        Robert A. Heinlein  1956
3             call him dead        Eric Frank Russell  1956
4       the end of eternity              Isaac Asimov  1956
..                      ...                       ...   ...
360    a drop of corruption    Robert Jackson Bennett  2026
361         the everlasting            Alix E. Harrow  2026
362        the incandescent                Emily Tesh  2026
363       the raven scholar           Antonia Hodgson  2026
364                  shroud        Adrian Tchaikovsky  2026

[365 rows x 3 columns]

In [124]:
locus.title = locus.title.apply(lambda x : x.strip('“').strip('”'))
locus.title = locus.title.apply(lambda x : x.lower())
locus.head()

                       title             author  year
0                  ringworld        Larry Niven  1971
1             tower of glass  Robert Silverberg  1971
2  the year of the quiet sun      Wilson Tucker  1971
3             and chaos died        Joanna Russ  1971
4      downward to the earth  Robert Silverberg  1971

In [125]:
hugo_mask = books.author.isin(hugo.author) & books.title.isin(hugo.title)
locus_mask = books.author.isin(locus.author) & books.title.isin(locus.title)

In [126]:
books['hugo'] = hugo_mask
books['locus'] = locus_mask

In [127]:
for title in hugo.title:
    if len(books.loc[books.title == title]) == 0:
        print(title, ':', hugo[hugo.title == title].author.iloc[0])

call him dead : Eric Frank Russell
have space suit -- will travel : Robert A. Heinlein
sylva : Vercors
dune world : Frank Herbert
beggars and choosers : Nancy Kress
to say nothing of the dog : Connie Willis
harry potter and the prisoner of azkaban : J. K. Rowling
harry potter and the goblet of fire : J. K. Rowling
eifelheim : Michael Flynn
his majesty's dragon : Naomi Novik
blackout/all clear : Connie Willis
the wheel of time : Robert Jordan&Brandon Sanderson
the three-body problem : Cixin Liu
the goblin emperor : Katherine Addison
death's end : Cixin Liu
nettle & bone : T. Kingfisher
the adventures of amina al-sirafi : Shannon Chakraborty
a sorceress comes to call : T. Kingfisher

How to handle Blackout/All Clear? Seems to be two part novel, but database only seems to have All Clear

They put the whole of The Wheel of Time on here? There's like 5 billion of these books!

In [128]:
for title in locus.title:
    if len(books[books.title == title]) == 0:
        print(title, ":", locus[locus.title == title].author.iloc[0])

the doomsday gene : John Boyd
blake's progress : Ray Nelson
illuminatus! : Robert Shea&Robert Anton Wilson
all my sins remembered : Joe Haldeman
the silmarillion : J. R. R. Tolkien
the chronicles of thomas covenant the unbeliever : Stephen R. Donaldson
silver on the tree : Susan Cooper
stardance ii : Spider Robinson&Jeanne Robinson
catacomb years : Michael Bishop
tales of nevèrÿon : Samuel R. Delany
king david's spaceship : Jerry Pournelle
lycanthia : Tanith Lee
journey behind the wind : Patricia Wrightson
roderick : John Sladek
oh susannah! : Kate Wilhelm
elfstones of shannara : Terry Brooks
lyonesse : Jack Vance
neveryóna : Samuel R. Delany
the neverending story : Michael Ende
enchanter's end game : David Eddings
the businessman : Thomas M. Disch
fire and hemlock : Diana Wynne Jones
the beggar queen : Lloyd Alexander
the cat who walks through walls : Robert A. Heinlein
the book of kells : R. A. MacAvoy
lyonesse ii: the green pearl : Jack Vance
mulengro : Charles de Lint
wizard of the pigeons : Megan Lindholm
santiago : Mike Resnick
lear's daughters : M. Bradley KelloggwithWilliam Rossow
wizard of the pigeons : Megan Lindholm
magic kingdom for sale--sold! : Terry Brooks
new york by knight : Esther M. Friesner
the king of ys: roma mater : Poul Anderson&Karen Anderson
the unconquered country : Geoff Ryman
yarrow : Charles de Lint
the secret ascension : Michael Bishop
code blue — emergency! : James White
the awakeners:northshore; southshore : Sheri S. Tepper
the dark tower ii: the drawing of the three : Stephen King
orphan of creation : Roger MacBride Allen
the reindeer people : Megan Lindholm
stranger in a strange land [expanded edition](original uncut edition) : Robert A. Heinlein
in the country of the blind : Michael F. Flynn
agviq : Michael Armstrong
good omens : Terry Pratchett&Neil Gaiman
ghostwood : Charles de Lint
cloven hooves : Megan Lindholm
was : Geoff Ryman
the gypsy : Steven Brust&Megan Lindholm
the wizard's apprentice : S. P. Somtow
dragon star book iii: skybowl : Melanie Rawn
beggars and choosers : Nancy Kress
worldwar: in the balance : Harry Turtledove
memory & dream : Charles de Lint
exiles 1: the ruins of ambrai : Melanie Rawn
worldwar: tilting the balance : Harry Turtledove
waking the moon(revised) : Elizabeth Hand
the silent strength of stones : Nina Kiriki Hoffman
otherland: city of golden shadow : Tad Williams
nadya: the wolf chronicles : Pat Murphy
the golden compass(uk title:northern lights) : Philip Pullman
einstein's bridge : John Cramer
the dark tower iv: wizard and glass : Stephen King
the subtle knife : Philip Pullman
gate of ivory :  Gate of Horn
to say nothing of the dog : Connie Willis
otherland: river of blue fire : Tad Williams
dark lord of derkholm : Diana Wynne Jones
harry potter and the philosopher's stone(us title:harry potter and the sorcerer's stone) : J. K. Rowling
harry potter and the prisoner of azkaban : J. K. Rowling
the sub : Thomas M. Disch
rhapsody : Elizabeth Haydon
the amber spyglass : Philip Pullman
ash: a secret history : Mary Gentle
daemonomania : John Crowley
harry potter and the goblet of fire : J. K. Rowling
metaplanetary : Tony Daniel
whole wide world : Paul McAuley
otherland: sea of silver light : Tad Williams
lirael : Garth Nix
the house in the high woold : Jeffrey E. Barlough
the golden age: the phoenix exultant; the golden transcendence : John C. Wright
succession: the risen empire; the killing of worlds : Scott Westerfeld
felaheen: the third arabesk : Jon Courtenay Grimwood
the dark tower v: wolves of the calla : Stephen King
lost boy lost girl : Peter Straub
the fourth circle : Zoran Zivkovic
spondulix : Paul Di Filippo
the wizard knight : Gene Wolfe
the dark tower: song of susannah : Stephen King
one king, one soldier : Alexander C. Irvine
the carpet makers : Andreas Eschbach
eifelheim : Michael Flynn
ilario: the lion's eye : Mary Gentle
temeraire: his majesty's dragon/throne of jade/black powder war : Naomi Novik
engineer trilogy: devices and desires/evil for evil/the escapement : K. J. Parker
blood engines : T. A. Pratt
the quiet war : Paul McAuley
the january dancer : Michael Flynn
the company : K. J. Parker
shadowbridge/lord tophet : Gregory Frost
memoirs of a master forger : William Heaney
gardens of the sun : Paul McAuley
buyout : Alexander C. Irvine
cloud & ashes: three winter's tales : Greer Gilman
spell games : T. A. Pratt
dragon in chains : Daniel Fox
blackout/all clear : Connie Willis
the folding knife : K. J. Parker
jade man's skin : Daniel Fox
caliban's war : James S. A. Corey
fate of worlds : Larry Niven&Edward M. Lerner
in the mouth of the whale : Paul McAuley
sharps : K. J. Parker
abaddon's gate : James S. A. Corey
id: the second machine dynasty : Madeline Ashby
evening's empires : Paul McAuley
the cusanus game : Wolfgang Jeschke
blood oranges : Kathleen Tierney
anno dracula 1976-1991: johnny alucard : Kim Newman
the three-body problem : Cixin Liu
annihilation/authority/acceptance : Jeff VanderMeer
cibola burn : James S. A. Corey
the memory of sky : Robert Reed
the goblin emperor : Katherine Addison
resurrections : Roz Kaveney
death's end : Cixin Liu
babylon's ashes : James S. A. Corey
the last days of new paris : China Miéville
raven strategem : Yoon Ha Lee
the wonder engine : T. Kingfisher
ahab's return : Jeffrey Ford
the rosewater insurrection/the rosewater redemption : Tade Thompson
war of the maps : Paul McAuley
the angel of the crows : Katherine Addison
the galaxy :  and the Ground Within
leviathan falls : James S. A. Corey
the witness for the dead : Katherine Addison
paladin's strength : T. Kingfisher
no gods :  No Monsters
nettle & bone : T. Kingfisher
the grief of stones : Katherine Addison
paladin's faith : T. Kingfisher
to shape a dragon's breath : Moniquill Blackgoose
my mother's keeper : Tim Powers
the mercy of gods : James S. A. Corey
a sorceress comes to call : T. Kingfisher
slow gods : Claire North
hemlock & silver : T. Kingfisher
the tomb of dragons : Katherine Addison

How do we handle the Illuminatus! Trilogy? It seems the database has them as three separate books, but the Locus award lists them as one entry.

The entry in the database is the Quenta Silmarillion. I'm not sure if we should count that the same as the Silmarillion?

The Chronicles of Thomas Covenant the Unbeliever is a book series, while the full database has the individual books. How should we handle?

Starseed seems to be the Stardance II that's included in the Locus awards, but I'm not sure so hopefully someone who knows more can help me deliberate. Or maybe not? Wikipedia lists Stardance II as the serialized conclusion to the novella Stardance. Now I don't know what to think here. 

Also I believe we can combine the entries of the Stardance series in the combined database because they are cowritten by Spider and Jeanne Robinson, but are listed as separate entries in the full database.