This notebook explores and cleans 'final_book_dataset.csv'.
I specifically:
- Removed the column index column
- Turned all entries in title_id into integers
- Turned all author birthyears into integers
- Turned all isbns into strings, so hopefully we get less warnings about this column's dtypes
- I also parsed the raw HTML book_synopsis entries using html2text. Hopefully this results in something better to use

In [21]:
import numpy as np
import pandas as pd

In [22]:
books = pd.read_csv('final_book_dataset.csv', sep='\t')
books = books[['title_id', 'title', 'author', 'release_year',
       'release_date', 'first_publisher', 'author_birthyear',
       'author_birthplace', 'isbn', 'book_synopsis', 'tags', 'hugo', 'locus']]

/tmp/ipykernel_28341/3878242122.py:1: DtypeWarning: Columns (0: isbn) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('final_book_dataset.csv', sep='\t')

In [23]:
books.title_id = books.title_id.astype('Int64')
books.author_birthyear = books.author_birthyear.astype('Int64')
books.isbn = books.isbn.astype('str')
books.sample(5)

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus
37895,1318938,The Chosen One,Kenneth E. Baker,2004,2004-00-00,Whiskey Creek Press,<NA>,NaN,1593741014,NaN,['Science fiction'],False,False
75127,2141910,Siege of Night,Jeff Gunzel,2014,2014-01-19,Jeff Gunzel,<NA>,NaN,NaN,NaN,['fantasy'],False,False
83835,1808357,Homecoming,Kass Morgan,2015,2015-02-24,"Little, Brown",1984,"New York City, New York, USA",9780316381963.0,Humanity is coming home. Weeks after landing o...,"['young-adult sf', 'Juvenile Fiction', 'Young ...",False,False
117274,2611583,Shields in Shadow,Andy Peloquin,2019,2019-08-19,Andy Peloquin,<NA>,Japan,9781686195921.0,NaN,['military fantasy'],False,False
103678,3211308,Dead Reckoning,"Jack Colrain, Grace Hamilton",2018,2018-06-14,Relay Publishing,<NA>,NaN,9781721136407.0,NaN,NaN,False,False

In [24]:
# Use html2text to parse the descriptions
# Install only once of course
#%pip install -U html2text

In [25]:
import html2text

def exception_handled_htmlparse(x):
    try:
        return html2text.html2text(x)
    except AttributeError:
        if pd.isnull(x):
            return ''
        print(x)
    return x

In [26]:
books.book_synopsis = books.book_synopsis.apply(exception_handled_htmlparse)

In [27]:
books

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus
0,9372,The Long Loud Silence,Wilson Tucker,1954,1954-00-00,Dell,1914,"Deer Creek, Illinois, USA",0899683754,Publisher's description: Tomorrow's war -- the...,"['Anatomy of Wonder 1 Core Collection', 'biolo...",False,False
1,2215181,Mrs. Candy Strikes It Rich,Robert Tallant,1954,1954-00-00,Doubleday,1909,"New Orleans, Louisiana, USA",NaN,,NaN,False,False
2,1392436,Return to the Lost Planet,Angus MacVicar,1954,1954-00-00,Burke,1908,"Duror, Argyll, Scotland, UK",NaN,,NaN,False,False
3,1112206,Rainbow on the Road,Esther Forbes,1954,1954-00-00,Houghton Mifflin,1891,"Westborough, Massachusetts, USA",NaN,,NaN,False,False
4,1908,The Forgotten Planet,Murray Leinster,1954,1954-00-00,Ace Books,1896,"Norfolk, Virginia, USA",0881846163,"**From the first page of the Ace Double:** ""Na...","['insects', 'Librivox', 'Project Gutenberg', '...",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151586,3506914,Daughter of the Underworld,"Katharine Corr, Elizabeth Corr",2025,2025-09-09,Candlewick Press,<NA>,NaN,9781536244533.0,"Join a thrilling journey into the Underworld, ...","['Young Adult Fiction', 'Fantasy', 'Young Adul...",False,False
151587,3506911,We Are Always Tender with Our Dead,Eric LaRocca,2025,2025-09-09,Titan Books,<NA>,"Connecticut, USA",9781803368672.0,A chilling supernatural tale of transgressive ...,"['Fiction', 'LGBTQ', 'Fantasy', 'TBB The Grave...",False,False
151588,3506908,They Fear Not Men in the Woods,Gretchen McNeil,2025,2025-09-09,DAW Books,1983,"San Francisco, California, USA",9780756420086.0,When Jen Monroe hears her father's remains hav...,['Fiction'],False,False
151589,3506905,Press 1 for Invasion,J. A. Dauber,2025,2025-09-09,Aladdin,<NA>,NaN,9781665974776.0,,['juvenile sf'],False,False
151590,<NA>,The Tomb of Dragons,Katherine Addison,2025,NaN,Tor Books,<NA>,NaN,9781250821027.0,Thara Celehar has lost his ability to speak wi...,"['Fantasy', 'Fiction', 'Science Fiction', 'LGB...",False,True

In [28]:
books.to_csv('final_book_dataset_cleaned.csv', sep='\t', index=False)

In [32]:
test = pd.read_csv('final_book_dataset_cleaned.csv', dtype={'isbn' : 'str'}, sep='\t')

In [33]:
test

,title_id,title,author,release_year,release_date,first_publisher,author_birthyear,author_birthplace,isbn,book_synopsis,tags,hugo,locus
0,9372.0,The Long Loud Silence,Wilson Tucker,1954,1954-00-00,Dell,1914.0,"Deer Creek, Illinois, USA",0899683754,Publisher's description: Tomorrow's war -- the...,"['Anatomy of Wonder 1 Core Collection', 'biolo...",False,False
1,2215181.0,Mrs. Candy Strikes It Rich,Robert Tallant,1954,1954-00-00,Doubleday,1909.0,"New Orleans, Louisiana, USA",NaN,NaN,NaN,False,False
2,1392436.0,Return to the Lost Planet,Angus MacVicar,1954,1954-00-00,Burke,1908.0,"Duror, Argyll, Scotland, UK",NaN,NaN,NaN,False,False
3,1112206.0,Rainbow on the Road,Esther Forbes,1954,1954-00-00,Houghton Mifflin,1891.0,"Westborough, Massachusetts, USA",NaN,NaN,NaN,False,False
4,1908.0,The Forgotten Planet,Murray Leinster,1954,1954-00-00,Ace Books,1896.0,"Norfolk, Virginia, USA",0881846163,"**From the first page of the Ace Double:** ""Na...","['insects', 'Librivox', 'Project Gutenberg', '...",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151586,3506914.0,Daughter of the Underworld,"Katharine Corr, Elizabeth Corr",2025,2025-09-09,Candlewick Press,NaN,NaN,9781536244533.0,"Join a thrilling journey into the Underworld, ...","['Young Adult Fiction', 'Fantasy', 'Young Adul...",False,False
151587,3506911.0,We Are Always Tender with Our Dead,Eric LaRocca,2025,2025-09-09,Titan Books,NaN,"Connecticut, USA",9781803368672.0,A chilling supernatural tale of transgressive ...,"['Fiction', 'LGBTQ', 'Fantasy', 'TBB The Grave...",False,False
151588,3506908.0,They Fear Not Men in the Woods,Gretchen McNeil,2025,2025-09-09,DAW Books,1983.0,"San Francisco, California, USA",9780756420086.0,When Jen Monroe hears her father's remains hav...,['Fiction'],False,False
151589,3506905.0,Press 1 for Invasion,J. A. Dauber,2025,2025-09-09,Aladdin,NaN,NaN,9781665974776.0,NaN,['juvenile sf'],False,False
151590,NaN,The Tomb of Dragons,Katherine Addison,2025,NaN,Tor Books,NaN,NaN,9781250821027.0,Thara Celehar has lost his ability to speak wi...,"['Fantasy', 'Fiction', 'Science Fiction', 'LGB...",False,True