In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
missing_list = pd.read_csv("missing_books.csv", delimiter='\t')
len(missing_list)

101

In [3]:
missing_finalists = pd.read_csv('missing_book_details.csv', delimiter='\t')
missing_finalists

# we see that there are duplicate editions and

,batch_num,isbn,title,author,release_year,publisher,description,tags
0,3,9.781430e+12,Eifelheim,Michael Flynn,2006,Macmillan,**The alien world of medieval Europe lives aga...,"[{'Science Fiction': 2}, {'Young Adult': 1}, {..."
1,3,9.780765e+12,Eifelheim,Michael Flynn,2006,Macmillan,**The alien world of medieval Europe lives aga...,"[{'Science Fiction': 2}, {'Young Adult': 1}, {..."
2,4,9.788072e+12,Drak Jeho Veličenstva,Naomi Novik,2005,HarperCollins UK,Aerial combat brings a thrilling new dimension...,"[{'Fantasy': 3}, {'Fiction': 2}, {'Science Fic..."
3,4,NaN,His Majesty's Dragon,Naomi Novik,2005,Random House Audio,Aerial combat brings a thrilling new dimension...,"[{'Fantasy': 3}, {'Fiction': 2}, {'Science Fic..."
4,4,9.780739e+12,His Majesty's Dragon,Naomi Novik,2005,RH Audio,Aerial combat brings a thrilling new dimension...,"[{'Fantasy': 3}, {'Fiction': 2}, {'Science Fic..."
...,...,...,...,...,...,...,...,...
356,100,9.781251e+12,The Tomb of Dragons,Katherine Addison,2025,Tor Books,Thara Celehar has lost his ability to speak wi...,"[{'Fantasy': 4}, {'Fiction': 2}, {'Science Fic..."
357,100,9.781838e+12,The Tomb of Dragons,Katherine Addison,2025,Solaris,Thara Celehar has lost his ability to speak wi...,"[{'Fantasy': 4}, {'Fiction': 2}, {'Science Fic..."
358,100,9.781251e+12,The Tomb of Dragons,Katherine Addison,2025,Tor Books,Thara Celehar has lost his ability to speak wi...,"[{'Fantasy': 4}, {'Fiction': 2}, {'Science Fic..."
359,100,9.781251e+12,The Tomb of Dragons,Katherine Addison,2025,Tor Books,Thara Celehar has lost his ability to speak wi...,"[{'Fantasy': 4}, {'Fiction': 2}, {'Science Fic..."
360,100,9.781250e+12,The Tomb of Dragons,Katherine Addison,2025,Macmillan Audio,Thara Celehar has lost his ability to speak wi...,"[{'Fantasy': 4}, {'Fiction': 2}, {'Science Fic..."

In [4]:
locus = pd.read_csv('locus_nominees.csv')
hugo = pd.read_csv('hugo_nominees.csv')
hugo_mask = missing_finalists.author.isin(hugo.author) & missing_finalists.title.isin(hugo.title)
locus_mask = missing_finalists.author.isin(locus.author) & missing_finalists.title.isin(locus.title)

missing_finalists['hugo'] = hugo_mask
missing_finalists['locus'] = locus_mask

In [5]:
# get rid of any accidental non-matches

missing_finalists = missing_finalists[~((missing_finalists['hugo'] == False) & (missing_finalists['locus'] == False))]

In [6]:
# de-duplicate editions, taking the first published 
missing_finalists = missing_finalists.drop_duplicates(['title', 'author'], keep='first')

In [7]:
missing_finalists.head(5)

,batch_num,isbn,title,author,release_year,publisher,description,tags,hugo,locus
0,3,9.781430e+12,Eifelheim,Michael Flynn,2006,Macmillan,**The alien world of medieval Europe lives aga...,"[{'Science Fiction': 2}, {'Young Adult': 1}, {...",True,True
3,4,NaN,His Majesty's Dragon,Naomi Novik,2005,Random House Audio,Aerial combat brings a thrilling new dimension...,"[{'Fantasy': 3}, {'Fiction': 2}, {'Science Fic...",True,False
22,8,NaN,The Three-Body Problem,Cixin Liu,2006,Head of Zeus,An alien civilization on the brink of destruct...,"[{'Science Fiction': 17}, {'Fiction': 7}, {'Al...",True,True
47,9,9.781430e+12,The Goblin Emperor,Katherine Addison,2014,Tor Books,"The youngest, half-goblin son of the Emperor h...","[{'Fantasy': 8}, {'Fiction': 2}, {'Science Fic...",True,True
57,10,NaN,Death's End,Cixin Liu,2008,Tor Books,"Half a century after the Doomsday Battle, the ...","[{'Science Fiction': 11}, {'Fiction': 3}, {'Fa...",True,True

In [8]:
import ast 
def get_tags(b):
    if pd.isna(b):
        return np.nan
    b_dict = ast.literal_eval(b)
    b_keys =  [list(item.keys())[0] for item in b_dict]
    return b_keys
    

missing_finalists['tags'] = missing_finalists['tags'].apply(get_tags)

In [9]:
missing_finalists['first_publisher'] = missing_finalists['publisher']
missing_finalists['isbn'].apply(lambda x: np.nan if np.isnan(x) else str(x) )
missing_finalists['release_year'].apply(lambda x: np.nan if np.isnan(x) else int(x) )
missing_finalists['book_synopsis'] = missing_finalists['description']

In [10]:
missing_finalists = missing_finalists.drop(['batch_num', 'description', 'publisher'], axis=1)

In [11]:
missing_finalists

,isbn,title,author,release_year,tags,hugo,locus,first_publisher,book_synopsis
0,9.781430e+12,Eifelheim,Michael Flynn,2006,"[Science Fiction, Young Adult, Fiction, Fantas...",True,True,Macmillan,**The alien world of medieval Europe lives aga...
3,NaN,His Majesty's Dragon,Naomi Novik,2005,"[Fantasy, Fiction, Science Fiction, War, Young...",True,False,Random House Audio,Aerial combat brings a thrilling new dimension...
22,NaN,The Three-Body Problem,Cixin Liu,2006,"[Science Fiction, Fiction, Aliens, Fantasy, Sc...",True,True,Head of Zeus,An alien civilization on the brink of destruct...
47,9.781430e+12,The Goblin Emperor,Katherine Addison,2014,"[Fantasy, Fiction, Science Fiction & Fantasy, ...",True,True,Tor Books,"The youngest, half-goblin son of the Emperor h..."
57,NaN,Death's End,Cixin Liu,2008,"[Science Fiction, Fiction, Fantasy, Dystopian,...",True,True,Tor Books,"Half a century after the Doomsday Battle, the ..."
72,9.781789e+12,Nettle & Bone,T. Kingfisher,2022,"[Fantasy, Fiction, Horror, Young Adult, Advent...",True,True,Titan Books,After years of seeing her sisters suffer at th...
82,NaN,A Sorceress Comes to Call,T. Kingfisher,2024,"[Fantasy, Fiction, Science Fiction, Young Adul...",True,True,Macmillan Audio,*The hardcover edition features a foil stamp o...
92,9.780312e+12,All My Sins Remembered,Joe Haldeman,1977,"[Science Fiction, Fantasy, Space, Aliens, Adve...",False,True,St. Martin's Press,Otto McGavin is peaceful and idealistic by nat...
95,9.780553e+12,Tales of Nevèrÿon,Samuel R. Delany,1979,"[Fiction, Fantasy, Classics, Science fiction, ...",False,True,Bantam Books,A group of interrelated stories taking place i...
101,9.780709e+12,King David's Spaceship,Jerry Pournelle,1973,"[Adventure, Fiction, Science Fiction, Space, ...",False,True,Futura,Four levels of technology collide in this fasc...
112,9.780140e+12,The Neverending Story,Michael Ende,1979,"[Fantasy, Young Adult, Juvenile Fiction, Ficti...",False,True,Putnam Juvenile,This epic work of the imagination has captured...
131,9.780425e+12,The Businessman,Thomas M. Disch,1984,[],False,True,NaN,NaN
132,9.780553e+12,The Book of Kells,R. A. MacAvoy,1985,"[Classics, Fantasy, Adventure, Science Fiction...",False,True,Spectra,An unusual and original work of fantasy from t...
133,9.780747e+12,New York by Knight,Esther M. Friesner,1986,"[Fantasy, Adventure, Science Fiction]",False,True,Headline,NaN
134,9.780007e+12,The Reindeer People,Megan Lindholm,1988,"[Fiction, Fantasy, Adventure, Science fiction]",False,True,HarperCollins UK,A voyage of discovery into the life of a remot...
135,NaN,Ghostwood,Charles de Lint,1990,[Fantasy],False,True,Axolotl Press,NaN
136,9.780008e+12,Cloven Hooves,Megan Lindholm,1991,"[Fantasy, Fiction]",False,True,HarperCollins UK,"Evelyn is a solitary child, preferring to wand..."
143,9.780575e+12,The Wizard Knight,Gene Wolfe,2005,"[Fantasy, Science Fiction]",False,True,Gollancz,"“Gene Wolfe is the smartest, subtlest, most da..."
145,9.780765e+12,The Carpet Makers,Andreas Eschbach,1995,"[Classics, German fiction]",False,True,Macmillan,"The carpet maker, following the traditions of ..."
150,9.780575e+12,The Quiet War,Paul McAuley,2008,"[Science fiction, Fantasy, Fiction, Space, War]",False,True,Gollancz,"23rd century Earth, ravaged by climate change,..."
152,9.780575e+12,Gardens of the Sun,Paul McAuley,2009,"[Fantasy, Adventure, Fiction, Science fiction,...",False,True,Gollancz,The Quiet War is over. The city states of the ...
153,9.781619e+12,Cloud & Ashes: Three Winter's Tales,Greer Gilman,2009,"[Fantasy, Fiction]",False,True,Small Beer Press,Winner of the Tiptree Award and a Mythopoeic A...
154,9.780316e+12,Caliban's War,James S. A. Corey,2012,"[Science Fiction, Fantasy, Sci-fi, Science Fic...",False,True,Orbit,"We are not alone. On Ganymede, breadbasket of ..."
172,9.780575e+12,In the Mouth of the Whale,Paul McAuley,2012,"[Fantasy, Science fiction, War, Fiction]",False,True,Gollancz,"In the system of Fomalhaut, a war is being fou..."
174,NaN,Abaddon's Gate,James S. A. Corey,2013,"[Science Fiction, Adventure, Fantasy, Sci-fi, ...",False,True,Hachette Audio,The third book in the NYT bestselling Expanse ...
186,9.780575e+12,Evening's Empires,Paul McAuley,2013,"[Fantasy, Fiction, Adventure, Science fiction]",False,True,Gollancz,"In the far future, a young man stands on a bar..."
189,9.780451e+12,Blood Oranges,Kathleen Tierney,2013,"[Fantasy, Fiction, Horror, drug addicts, demon...",False,True,Roc,My name’s Quinn.\n\nIf you buy into my reputat...
239,9.781479e+12,Babylon's Ashes,James S. A. Corey,2016,"[Science Fiction, Fantasy, Fiction, Adventure,...",False,True,Orbit Books,A revolution brewing for generations has begun...
249,9.780346e+12,The Last Days of New Paris,China Miéville,2016,"[Science Fiction, Fantasy, War, Dystopian, Fic...",False,True,NaN,"""A thriller of war that never was--of survival..."
255,NaN,The Wonder Engine,T. Kingfisher,2018,"[Fantasy, Adventure, Fiction, Science Fiction,...",False,True,Red Wombat Studio,Pull three people out of prison--a disgraced p...
260,9.781473e+12,War of the Maps,Paul McAuley,2020,"[Fantasy, Science Fiction]",False,True,Gollancz,On a giant artificial world surrounding an art...
264,9.781781e+12,The Angel of the Crows,Katherine Addison,2020,"[Fantasy, Adventure, Science Fiction, LGBTQ, N...",False,True,Solaris,This is not the story you think it is. These a...
267,9.781491e+12,Leviathan Falls,James S. A. Corey,2021,"[Science Fiction, Fantasy, Aliens, Adventure, ...",False,True,"Recorded Books, Inc","The Laconian Empire has fallen, setting the th..."
278,9.780765e+12,The Witness for the Dead,Katherine Addison,2021,"[Fantasy, LGBTQ, Fiction, Mystery, Suspense, S...",False,True,Tor Books,A standalone novel in the fantastic world of K...
284,9.780357e+12,Paladin's Strength,T. Kingfisher,2021,"[Fantasy, Romance, Adventure, Fiction, Science...",False,True,Orbit Books,From the Hugo and Nebula Award winning author ...
305,9.781251e+12,The Grief of Stones,Katherine Addison,2022,"[Fantasy, LGBTQ, Young Adult, Fiction, Science...",False,True,Tor Books,"In The Grief of Stones, Katherine Addison retu..."
312,9.781615e+12,Paladin's Faith,T. Kingfisher,2023,"[Fantasy, Adventure, Fiction, Romance, Strong ...",False,True,Argyll Productions,Marguerite Florian has spent her life acquirin...
318,9.780594e+12,To Shape a Dragon's Breath,Moniquill Blackgoose,2023,"[Fantasy, Young Adult, Adventure, LGBTQ, Ficti...",False,True,Random House Audio,A young Indigenous woman enters a colonizer-ru...
321,9.781665e+12,The Mercy of Gods,James S. A. Corey,2024,"[Science Fiction, Fiction, Space, War, Aliens,...",False,True,"Recorded Books, Inc. and Blackstone Publishing","""The Carryx – part empire, part hive – have wa..."
342,9.780317e+12,Slow Gods,Claire North,2025,"[Science Fiction, Fiction, Space, Unloveable C...",False,True,Orbit,"In telling my story, there are certain things ..."
349,9.781250e+12,Hemlock & Silver,T. Kingfisher,2025,"[Fantasy, Fiction, Dark Fantasy, Adventure, Lo...",False,True,Tor Books,Healer Anja knows little of politics but much ...
356,9.781251e+12,The Tomb of Dragons,Katherine Addison,2025,"[Fantasy, Fiction, Science Fiction, LGBTQ, Adv...",False,True,Tor Books,Thara Celehar has lost his ability to speak wi...

In [12]:
previous_dataset = pd.read_csv('isfdb-hardcover-hugo.csv')

In [13]:
full_dataset = pd.concat([previous_dataset, missing_finalists], ignore_index=True)

In [14]:
# get rid of old index columns

full_dataset = full_dataset.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1)

In [15]:
full_dataset.columns

Index(['title_id', 'author', 'release_year', 'release_date',
       'author_age_at_release', 'author_birthplace', 'isbn', 'first_publisher',
       'book_synopsis', 'tags', 'title', 'hugo', 'locus'],
      dtype='str')

In [16]:
# reordering columns a bit
full_dataset = full_dataset[['title_id', 'title', 'author', 'release_year', 'release_date', 'first_publisher',
       'author_age_at_release', 'author_birthplace', 'isbn', 
       'book_synopsis', 'tags',  'hugo', 'locus']]

In [18]:
full_dataset.to_csv("final_book_dataset.csv", sep='\t')